### ISSUE TITLE
Pipelining and streaming

### ISSUE THREAD

**Issue by Zehaos** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#1014]
hi, Does MIVisionX support Pipelining and streaming?

**Comment by rrawther** [comment]
Hi Zehaos, Can you please elaborate on your use case? Pipelining and streaming is too generic words.

**Comment by kiritigowda** [comment]
Hi @Zehaos did you get a chance to see the comment above?

**Comment by kiritigowda** [comment]
Hi @Zehaos please reopen this issue if you are still missing any information you need. Thanks!
