### ISSUE TITLE
rocal_pybind - import Module fails

### ISSUE THREAD

**Issue by LakshmiKumar23** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#1015]
@swetha097  @shobana-mcw Can you have a look at this?
Fails on docker and bare metal with ImportError or ModuleNotFound 
Test on example training scripts as well as ```PYTHON_UNITTEST_TEST_FILE.sh```

Bare-metal - ubuntu22.04/ python3.10:
```
Traceback (most recent call last):
  File "/home/svcbuild/test/MIVisionX/rocAL/rocAL_pybind/examples/tf_petsTrainingExample/train_withROCAL_withTFRecordReader.py", line 22, in <module>
    from amd.rocal.plugin.tf import ROCALIterator
  File "/home/svcbuild/.local/lib/python3.10/site-packages/amd/rocal/plugin/tf.py", line 22, in <module>
    import rocal_pybind as b
ImportError: /opt/rocm-5.4.0/lib/libamd_rpp.so: undefined symbol: _ZN5boost10filesystem6detail11dir_itr_impD1Ev
```

Docker - ubuntu20.04/python3.8:
```
Traceback (most recent call last):
  File "test_training.py", line 28, in <module>
    from amd.rocal.plugin.pytorch import ROCALClassificationIterator
  File "/opt/conda/lib/python3.8/site-packages/amd/rocal/plugin/pytorch.py", line 23, in <module>
    import rocal_pybind as b
ModuleNotFoundError: No module named 'rocal_pybind'
```

**Comment by LakshmiKumar23** [comment]
Update:
Error ```ImportError: /opt/rocm-5.4.0/lib/libamd_rpp.so: undefined symbol: _ZN5boost10filesystem6detail11dir_itr_impD1Ev```
is resolved on ub22 by installing boost 1.8 and building RPP again

**Comment by paveltc** [comment]
I'm getting the error:
ModuleNotFoundError: No module named 'amd'
when running from the pytorch mivisionx docker

**Comment by kiritigowda** [comment]
@LakshmiKumar23 any updates on this on TOT master MIVisionX?

**Comment by kiritigowda** [comment]
@LakshmiKumar23 can we close this issue?

**Comment by LakshmiKumar23** [comment]
@kiritigowda I don't see this issue any longer
