### ISSUE TITLE
Setup - Developer Install

### ISSUE THREAD

**Issue by kiritigowda** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#1022]
GDB 12.4+ - @asalmanp can you add install info

**Comment by asalmanp** [comment]
@kiritigowda please find the instructions below:

sudo apt update
sudo apt install build-essential texinfo
sudo apt-get install libgmp-dev
cd ~
wget https://ftp.gnu.org/gnu/gdb/gdb-12.1.tar.gz
tar -xvzf gdb-12.1.tar.gz
cd gdb-12.1
./configure --with-python
make CXXFLAGS="-static-libstdc++"  -j16
sudo make install -j16

**Comment by kiritigowda** [comment]
@asalmanp - on Ubuntu 22

`sudo apt-get install libc6-dbg gdb valgrind `

```
gdb -v
GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

can you confirm if this version is good ?

**Comment by kiritigowda** [comment]
PR #1025 adds support to gdb install
