### ISSUE TITLE
rocAL - MacOS failure

### ISSUE THREAD

**Issue by kiritigowda** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#1028]
TOT Master rocAL fails to build on MacOS.

@rrawther -- cpu_set_t data structure is just a 32-bit variable so the max number cores is 32. How do we handle 64 cores? Not sure if this is an issue

```
include/loaders/image/image_loader.h:47:41: error: unknown type name 'cpu_set_t'
    LoaderModuleStatus set_cpu_affinity(cpu_set_t cpu_mask);
                                        ^
include/loaders/video/video_loader.h:49:46: error: unknown type name 'cpu_set_t'
    VideoLoaderModuleStatus set_cpu_affinity(cpu_set_t cpu_mask);
```

**Comment by rrawther** [comment]
@kiritigowda : cpu_set_t is not 32 bit. It is a structure which 32 unsigned long. So total bits is 32x32.
I don't think this is an issue. rocAL is not using this function in runtime. So we can comment this out if this is an issue for MAC

**Comment by kiritigowda** [comment]
@rrawther thanks for the update. Maybe we can get deprecate the CPU_SET usage in rocAL for now as a fix.

**Comment by kiritigowda** [comment]
Issue moved to rocAL repo
