### ISSUE TITLE
LoomSL - Compilted loom_shell on win10 ,out error.

### ISSUE THREAD

**Issue by molyswu** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#1032]
Hi,
	Compilted loom_shell   on win10  and tools with  VS2017

Severity code description project file line suppression status
Error C2146 Syntax error: Missing ';' (in identifier“clGetExtensionFunctionAddressForPlatform”in front of)	loom_shell	e:\pcl\mivisionx\utilities\loom_shell\loom_shell_util.cpp	519	

Thanks !

**Comment by molyswu** [comment]
#if !__APPLE__
	clEnqueueWaitSignalAMD_fn clEnqueueWaitSignalAMD = (clEnqueueWaitSignalAMD_fn)clGetExtensionFunctionAddressForPlatform(platform_id[platform_index], "clEnqueueWaitSignalAMD");
	clEnqueueWriteSignalAMD_fn clEnqueueWriteSignalAMD = (clEnqueueWriteSignalAMD_fn)clGetExtensionFunctionAddressForPlatform(platform_id[platform_index], "clEnqueueWriteSignalAMD");
	clEnqueueMakeBuffersResidentAMD_fn clEnqueueMakeBuffersResidentAMD = (clEnqueueMakeBuffersResidentAMD_fn)clGetExtensionFunctionAddressForPlatform(platform_id[platform_index], "clEnqueueMakeBuffersResidentAMD");
	if (clEnqueueWaitSignalAMD && clEnqueueWriteSignalAMD && clEnqueueMakeBuffersResidentAMD) {
		direct_gma_available = true;
	}
#endif

**Comment by kiritigowda** [comment]
@molyswu -- Hi, I am unable to reproduce this issue both on W10/11. Did you install OpenCL? -- https://github.com/GPUOpen-LibrariesAndSDKs/OCL-SDK/releases/tag/1.0

Let me know if you can try the following prerequisites - https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX#windows

**Comment by kiritigowda** [comment]
@molyswu please reopen this issue if you are having problems building LOOM. Thanks!
