### ISSUE TITLE
Setup script - Add CuPy 

### ISSUE THREAD

**Issue by LakshmiKumar23** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#1037]
Add CuPy to all dockerfiles and setup script for rocAL
Instructions:
```
apt-get update
apt install -y hipblas hipsparse rocrand rocthrust hipcub git g++ hipfft rocfft python3-dev

#Install CuPy
git clone https://github.com/ROCmSoftwarePlatform/cupy.git && cd cupy
export CUPY_INSTALL_USE_HIP=1
export HCC_AMDGPU_TARGET=gfx90a (or need to identify and add any other target architectures comma-separated)
export ROCM_HOME=/opt/rocm
git submodule update --init
pip install -e . --no-cache-dir -vvvv
```

**Comment by kiritigowda** [comment]
@LakshmiKumar23 - exports with Python Script with target hardware might not work as expected, are all these exports required to build?

**Comment by LakshmiKumar23** [comment]
> @LakshmiKumar23 - exports with Python Script with target hardware might not work as expected, are all these exports required to build?

@kiritigowda These are the instructions I got from the team. I am guessing it's needed

**Comment by kiritigowda** [comment]
CuPy install added to develop - PR #1050

**Comment by kiritigowda** [comment]
@LakshmiKumar23 open a new issue to add CuPy to dockers, will merge develop to test.
