### ISSUE TITLE
rocAL - Add CuPy to dockers

### ISSUE THREAD

**Issue by LakshmiKumar23** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#1057]
@kiritigowda Need to add CuPy to dockerfiles (similar to setup script)

**Comment by kiritigowda** [comment]
CuPy added to Docker - https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/blob/386e7488d2f278c96ef81a71abb9f6353d8af4b2/docker/mivisionx-on-ubuntu22.dockerfile#L63 -- available on TOT
