### ISSUE TITLE
MIVisionX develop build is failing because of missing README.md file

### ISSUE THREAD

**Issue by rrawther** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#1071]
@kiritigowda @samjwu : I think the tot is not installing because of the following error
CMake Error at cmake_install.cmake:46 (file):
  file INSTALL cannot find "./MIVisionX/docs/README.md": No
  such file or directory.

**Comment by samjwu** [comment]
closed by https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/pull/1072
