### ISSUE TITLE
Model Compiler - ONNX model compiler errors

### ISSUE THREAD

**Issue by paveltc** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#1081]
I just ran a regression and found that the ONNX models started throwing errors when running onnx_to_nnir.py after PR 1070.
I checked alexnet 7 and it threw KeyError: 'fc6_3' after the change.
Prior to the change, the model ran all the way through anntest successfully.

**Comment by hansely** [comment]
PR #1082 fixes this issue
