### ISSUE TITLE
MIVisionX setup - OpenCV installation update

### ISSUE THREAD

**Issue by LakshmiKumar23** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#1097]
The following two libraries were missing on the MI300 and hence all OpenCV apps were failing on it. @kiritigowda Please add to the script.
```
 sudo apt install libgtk2.0-dev
sudo apt install pkg-config
```
rebuilding OpenCV after this and then rebuilding MIVisionX worked.

**Comment by kiritigowda** [comment]
PR #1105 - Installs packages with OpenCV install

**Comment by kiritigowda** [comment]
@LakshmiKumar23 reopen this issue if you face it again.

**Comment by LakshmiKumar23** [comment]
@kiritigowda Facing the issue even after installing above two libraries
```
OK: loaded 82 kernels from libvx_rpp.so
Remaining images 256
Augmented copies count 5
output width 112 output height 1120 color planes 3
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.6.0) /home/lakshmi/mivisionx-deps/opencv-4.6.0/modules/highgui/src/window_gtk.cpp:635: error: (-2:Unspecified error) Can't initialize GTK backend in function 'cvInitSystem'

Aborted (core dumped)

```

**Comment by kiritigowda** [comment]
@LakshmiKumar23 can you also try to use `ssh -Y` option to login before running the test. This should bypass any X11 related issue, if any.

**Comment by LakshmiKumar23** [comment]
@kiritigowda Setup rocm and everything on the system again from scratch. I do not see the error anymore. Closing the ticket
