### ISSUE TITLE
APP - OpenCV color inverted in image_augmentation app

### ISSUE THREAD

**Issue by paveltc** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#1149]
The color is inverted in the image_augmentation app, @kiritigowda says it is probably an OpenCV issue.
Command line:
./image_augmentation ../../data/images/AMD-tinyDataSet/ 1 224 224 0 1 1 1 0 2
@kiritigowda Ask me for the system info.

**Comment by kiritigowda** [comment]
@paveltc is this still an issue on the said system? I am not able reproduce this on any of my machine.

**Comment by kiritigowda** [comment]
@paveltc are you seeing this issue with TOT with rocm 5.7.0+ ?

**Comment by kiritigowda** [comment]
@paveltc please reopen if you see this again.
