### ISSUE TITLE
ERROR: kernel com.amd.nn_extension.reshape_layer exec failed (-1:(null))

### ISSUE THREAD

**Issue by hansely** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#1198]
Using vx_enum type to get the size of data type always returns 4 regardless of the actual data type.
e.g. 
```
sizeof(VX_TYPE_INT8) // expects 1
sizeof(VX_TYPE_FLOAT16) // expects 2
sizeof(VX_TYPE_FLOAT32) // expects 4
sizeof(VX_TYPE_FLOAT64) // expects 8
```
The above code lines all return 4.

This cause unexpected behavior especially when calculating the tensor memory size.
e.g.
```
vx_enum type;
ERROR_CHECK_STATUS(vxQueryTensor((vx_tensor)parameters[1], VX_TENSOR_DATA_TYPE, &type, sizeof(type)));
data->memsizeInBytes = dims[0]*dims[1]*dims[2]*dims[3]*sizeof(type);  // sizeof(type) always returns 4
```

**Comment by kiritigowda** [comment]
[VX_TYPE_FLOAT32](https://rocm.docs.amd.com/projects/MIVisionX/en/latest/doxygen/html/vx__types_8h.html#a44aa67e15168e5912a0800090a120be6aaa36bdf0ca05d4e93b1d5a4946570e16) is an enum def which is the 4 bytes. The vx_float16 is typedef to half. This will return 2

**Comment by hansely** [comment]
> [VX_TYPE_FLOAT32](https://rocm.docs.amd.com/projects/MIVisionX/en/latest/doxygen/html/vx__types_8h.html#a44aa67e15168e5912a0800090a120be6aaa36bdf0ca05d4e93b1d5a4946570e16) is an enum def which is the 4 bytes. The vx_float16 is typedef to half. This will return 2

Yes, will modify the code accordingly to match the expected behavior

**Comment by kiritigowda** [comment]
@hansely - you need to use [vx_int8](https://rocm.docs.amd.com/projects/MIVisionX/en/latest/doxygen/html/vx__types_8h.html#a4bb9840db3fea374224e831b2d3d868a), [vx_float32](https://rocm.docs.amd.com/projects/MIVisionX/en/latest/doxygen/html/vx__types_8h.html#af14ad5e46a20640307420a745d199e1d), & [vx_float64](https://rocm.docs.amd.com/projects/MIVisionX/en/latest/doxygen/html/vx__types_8h.html#a3718da3659bf64bccb45830294edc59e)

**Comment by kiritigowda** [comment]
@hansely - changing the issue name to reflect the PR fix.
