### ISSUE TITLE
Setup - CuPy update

### ISSUE THREAD

**Issue by LakshmiKumar23** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#1215]
@kiritigowda I spoke to CuPy team and seems like we need to update to the latest version. This works both Python3.8+
[Link ](https://confluence.amd.com/pages/viewpage.action?spaceKey=MLSE&title=CuPy+Unit+Test+Enablement) for updated page.

Prerequisites:
```
pip install scipy==1.9.3
pip install cython==0.29.*
# Install hipify torch
pip install git+https://github.com/ROCmSoftwarePlatform/hipify_torch.git
```
Branch to use: [rocm6.0_internal_testing](https://github.com/ROCmSoftwarePlatform/cupy/tree/rocm6.0_internal_testing)
```
git clone -b rocm6.0_internal_testing https://github.com/ROCmSoftwarePlatform/cupy
```

**Comment by kiritigowda** [comment]
@LakshmiKumar23 to be merged to master #1230, if issue persists reopen.
