### ISSUE TITLE
Can provide v1.2.0 Windows precompiled binaries?

### ISSUE THREAD

**Issue by oscarbg** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#130]
we have for v1.1: MIVisionX_WinML-installer.msi

**Comment by kiritigowda** [comment]
@oscarbg the precompiled windows binaries are added to the release - https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/releases/tag/1.2.0

**Comment by kiritigowda** [comment]
Binaries released with 1.2.0 for Windows. @oscarbg I am going to close this bug, please reopen or create a new bug if you find any new issues.

**Comment by oscarbg** [comment]
thanks!
