### ISSUE TITLE
NNIR update - convert fp16 doesn't build independently

### ISSUE THREAD

**Issue by LakshmiKumar23** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#141]
To reproduce error:

- Convert resnet50 caffe model to nnir
- do nnir update with convert-fp16
- do nnir update with fuse-ops
-run anntest - it fails

Doing both convert-fp16 and fuse-ops together builds

**Comment by rrawther** [comment]
Please check if this gets fixed after merging PR#142

**Comment by kiritigowda** [comment]
@LakshmiKumar23 can you check if this bug is fixed?

**Comment by LakshmiKumar23** [comment]
@kiritigowda Yes, it fixes the bug.

**Comment by kiritigowda** [comment]
PR #142 fix applied to master.
