### ISSUE TITLE
Preprocessing functionality for anntest

### ISSUE THREAD

**Issue by hansely** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#176]
Preprocessing functionality is needed for anntest to support certain models with normalized input.

**Comment by kiritigowda** [comment]
@hansely can you look into this issue?

**Comment by hansely** [comment]
Sure. Looking into it

**Comment by kiritigowda** [comment]
@hansely any updates on this issue?

**Comment by LakshmiKumar23** [comment]
@kiritigowda @paveltc was working on this

**Comment by paveltc** [comment]
@kiritigowda You, Hansel and I need to look at the preprocessing code. It is giving incorrect values for the probabilities.

**Comment by kiritigowda** [comment]
@hansely can we close this issue?
