### ISSUE TITLE
Fusion Bug - Neural Network

### ISSUE THREAD

**Issue by kiritigowda** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#195]
* Models have taken a performance hit

**Comment by kiritigowda** [comment]
@LakshmiKumar23 any update on this bug? need to close the issues with for rocm release tags for ROCm 3.0 Release.

**Comment by kiritigowda** [comment]
@LakshmiKumar23 can we close this bug?

**Comment by kiritigowda** [comment]
> @LakshmiKumar23 can we close this bug?

@LakshmiKumar23 any updates?

**Comment by LakshmiKumar23** [comment]
@kiritigowda I think this was fixed back in June/July. Can be closed.
