### ISSUE TITLE
OpenVX Framework - one question how to specify the GPU

### ISSUE THREAD

**Issue by paolodalberto** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#203]
I am using a prebuild example where yolo is applied to a mp4 video. The default device is GPU-0 because when the interface is created the device_id is by default 0. However, I have 3 GPUs available. 

I will introduce more details but I would like to ask if there is a way to drive the device assignment as global variable or  at python interface. The code I am using is based on the MIVisionX kit that I installed by the setup script.  If I use the runvx examples I can use the -affinity flag.

**Comment by paolodalberto** [comment]
OK: loaded 26 kernels from libvx_nn.so
OK: OpenVX using GPU device#0 (gfx803) [OpenCL 1.2 ] [SvmCaps 0 1]
OK: annCreateInference: successful

I would like to learn how to affect the device selection at this point.

**Comment by kiritigowda** [comment]
@paolodalberto the current OpenVX implementation is set to use the OpenCL device 0. The [code to set deviceID](https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/blob/9f6e9431f56995bec9f17564c694327c6926deb4/amd_openvx/openvx/ago/ago_util_opencl.cpp#L225).

You could also set different devices using the code sample in our app - [code](https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/blob/9f6e9431f56995bec9f17564c694327c6926deb4/apps/cloud_inference/server_app/arguments.cpp#L25)

**Comment by rrawther** [comment]
@paolodalberto, the way to do this is to create separate OpenVX and OpenCL contexts for each device and tie them together using vxSetContextAttribute(vx_context_for_device, VX_CONTEXT_ATTRIBUTE_AMD_OPENCL_CONTEXT, cl_context_for_device, flags). A use of this is shown in the above app mentioned by @kiritigowda

**Comment by paolodalberto** [comment]
let me see what I can do ... this is not my application so I am not familiar with it. 
In principle, I see in the code the ability of use environment variable you may consider to enhance the default setting.

**Comment by kiritigowda** [comment]
Here is an environmental variable to choose the target device - `AGO_OPENCL_PLATFORM`

A list of developer tools is compiled [here](https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/wiki/Developer-Tools:-OpenVX)

Feel free to reopen this issue if you still have problems.
