### ISSUE TITLE
Resnet: reproducing basic performance on Fiji 

### ISSUE THREAD

**Issue by paolodalberto** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#205]
I copied the resnet onnx files 
https://s3.amazonaws.com/onnx-model-zoo/resnet/resnet50v2/resnet50v2.onnx
https://s3.amazonaws.com/onnx-model-zoo/resnet/resnet50v1/resnet50v1.onnx

Let's start with resnet v2
```
+ BASE=/opt/rocm/mivisionx/model_compiler/python
+ python3 /opt/rocm/mivisionx/model_compiler/python/onnx_to_nnir.py resnet50v2.onnx Resnet-nnir --input-dims 1,3,224,224
loading ONNX model from resnet50v2.onnx ...
converting to IR model in Resnet-nnir ...
Traceback (most recent call last):
  File "/opt/rocm/mivisionx/model_compiler/python/onnx_to_nnir.py", line 210, in <module>
    main()
  File "/opt/rocm/mivisionx/model_compiler/python/onnx_to_nnir.py", line 207, in main
    onnx2ir(onnx_model_proto, outputFolder)
  File "/opt/rocm/mivisionx/model_compiler/python/onnx_to_nnir.py", line 191, in onnx2ir
    graph = onnx_graph_to_ir_graph(onnx_model.graph)
  File "/opt/rocm/mivisionx/model_compiler/python/onnx_to_nnir.py", line 180, in onnx_graph_to_ir_graph
    graph.updateLocals()
  File "/opt/rocm/mivisionx/model_compiler/python/nnir.py", line 407, in updateLocals
    raise ValueError("reshape: mismatch detected: " + node.inputs[0] + ":" + str(input.shape) + " " + node.outputs[0] + ":" + str(param))
ValueError: reshape: mismatch detected: resnetv24_pool1_fwd:[1, 2048, 1, 1] resnetv24_flatten0_reshape0:[1, 2, 1, 1]
```

any help ?

Then resnet v1
`+ BASE=/opt/rocm/mivisionx/model_compiler/python
+ python3 /opt/rocm/mivisionx/model_compiler/python/onnx_to_nnir.py resnet50v1.onnx Resnet-nnir
loading ONNX model from resnet50v1.onnx ...
converting to IR model in Resnet-nnir ...
OK: creating IR description in Resnet-nnir/graph.nnir ...
OK: creating IR binaries in Resnet-nnir/binary ...
+ python /opt/rocm/mivisionx/model_compiler/python/nnir_to_openvx.py Resnet-nnir Resnet-openVXModel
reading IR model from Resnet-nnir ...
OK: reading IR description from Resnet-nnir/graph.nnir ...
OK: reading IR binaries from Resnet-nnir/binary ...
#OUTPUT-TENSOR: resnetv17_dense0_fwd 1 1000 1 1 
creating C code in Resnet-openVXModel ...
creating Resnet-openVXModel/CMakeLists.txt ...
creating Resnet-openVXModel/cmake/FindOpenCL.cmake ...
creating Resnet-openVXModel/annmodule.h ...
creating Resnet-openVXModel/annmodule.cpp ...
creating Resnet-openVXModel/weights.bin ...
creating Resnet-openVXModel/anntest.cpp ...
creating Resnet-openVXModel/annpython.h ...
creating Resnet-openVXModel/annpython.cpp ...
creating Resnet-openVXModel/anntest.py ...
+ cd Resnet-openVXModel
+ mkdir -p build
+ cd build
+ cmake ..
-- Configuring done
-- Generating done
-- Build files have been written to: /home/paolo/FastMM/MIVisionX/ONNX/resnet50v1/Resnet-openVXModel/build
+ make
Scanning dependencies of target annmodule
[ 16%] Building CXX object CMakeFiles/annmodule.dir/annmodule.cpp.o
[ 33%] Linking CXX shared library libannmodule.so
[ 33%] Built target annmodule
Scanning dependencies of target annpython
[ 50%] Building CXX object CMakeFiles/annpython.dir/annpython.cpp.o
[ 66%] Linking CXX shared library libannpython.so
[ 66%] Built target annpython
Scanning dependencies of target anntest
[ 83%] Building CXX object CMakeFiles/anntest.dir/anntest.cpp.o
[100%] Linking CXX executable anntest
[100%] Built target anntest
`
Then I execute the test in two formats 

` ./build/anntest weights.bin 
OK: loaded 26 kernels from libvx_nn.so
ERROR: invalid data (magic,size)=(0xf00dd1e1,0) in weights.bin at byte position 4 -- expected size is 37632
ERROR: failed with status = (-1) at /home/paolo/FastMM/MIVisionX/ONNX/resnet50v1/Resnet-openVXModel/annmodule.cpp#993
ERROR: annAddToGraph() failed (-1)
`
and 
`python anntest.py ./build/libannpython.so  weights.bin  ~/Downloads/balls.jpeg out 
OK: AnnAPI found "input,data,1,3,224,224;output0,resnetv17_dense0_fwd,1,1000;" as configuration in ./build/libannpython.so
OK: loaded 26 kernels from libvx_nn.so
ERROR: annAddToGraph: failed (-1)
ERROR: annCopyToInferenceInput: invalid handle
INFO: annCopyToInferenceInput status -1
ERROR: annRunInference: invalid handle
INFO: annRunInference status -1 
Traceback (most recent call last):
  File "anntest.py", line 74, in <module>
    output,name,n,c,h,w = output_info.split(',')
ValueError: need more than 4 values to unpack
`

**Comment by paolodalberto** [comment]
I do not do any optimization ... I will ask about optimization shortly (fuse opt does not work for resnet or squeezenet, which is in the tutorial). 

Let me know how I can help ... thanks

**Comment by paolodalberto** [comment]
Another test: googlenet

https://s3.amazonaws.com/download.onnx/models/opset_9/bvlc_googlenet.tar.gz
compiled using
`BASE=/opt/rocm/mivisionx/model_compiler/python


python3 ${BASE}/onnx_to_nnir.py $2 nnir${1} --input_dims 1,3,224,224
python3 ${BASE}/nnir_update.py --fuse-ops 1 nnir${1} nnir${1}-Fused
python ${BASE}/nnir_update.py --convert-fp16 1  nnir${1}-Fused nnir${1}-Fused-2
python3 ${BASE}/nnir_to_openvx.py  nnir${1}-Fused-2 ${1}-openVXModel
cd ${1}-openVXModel
mkdir -p build && cd build
cmake ..
make
`
the optimization fp16 fails (I guess)
`python anntest.py build/libannpython.so weights.bin ~/Desktop/camera\ phone/small.jpg  out 
OK: AnnAPI found "input,data_0,1,3,224,224;output0,prob_1,1,1000;" as configuration in build/libannpython.so
OK: loaded 26 kernels from libvx_nn.so
ERROR: agoVerifyGraph: kernel org.khronos.nn_extension.convolution_layer: invalid tensor meta for argument#4
ERROR: vxVerifyGraph: failed (-17)
`

I can fuse the operation but there is no advantage.

**Comment by LakshmiKumar23** [comment]
@paolodalberto For resnet ONNX mode, we currently do not support v2. We support [https://s3.amazonaws.com/download.onnx/models/opset_8/resnet50.tar.gz]. (https://s3.amazonaws.com/download.onnx/models/opset_8/resnet50.tar.gz) from [https://github.com/onnx/models/tree/master/vision/classification/resnet/resnet50](https://github.com/onnx/models/tree/master/vision/classification/resnet/resnet50) which is release 1.3.

As for your question on googlenet, I haven't checked it yet. I will let you know once I look into it

**Comment by paolodalberto** [comment]
let me check if I can reproduce performance for the other resnet. I will work during the weekend.  
thank you.

**Comment by LakshmiKumar23** [comment]
@paolodalberto I tried the googlenet model you have specified with the latest MIVisionX and it passed our anntest. I believe you have an older version of MIVisionX since we have 32 kernels in libvx_nn.so now. Please pull the latest code. Yours specifies 26 (OK: loaded 26 kernels from libvx_nn.so)

**Comment by LakshmiKumar23** [comment]
@paolodalberto Any updates on the issue? Were you able to run the models?

**Comment by kiritigowda** [comment]
@paolodalberto please reopen the issue if you are having trouble with running the model.
