### ISSUE TITLE
Linux prerequisite error.

### ISSUE THREAD

**Issue by emerth** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#208]
This software needs a running X server even to simply run MIVisionX-setup.py. Which is fine. But people running GPU compute are often running headless...

How about adding "X Window" to the list of Linux prereqs?

**Comment by kiritigowda** [comment]
@emerth could you send a pull request for this? We can verify and merge it to the TOT. Thanks!

**Comment by emerth** [comment]
Sent. Thanks!

________________________________

**Comment by kiritigowda** [comment]
#217 Fix
