### ISSUE TITLE
MIVisionX - OpenVX 1.3 Support

### ISSUE THREAD

**Issue by kiritigowda** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#233]
# OpenVX 1.3 

## Vision Conformance Profile

* [x] - CPU Flow
* [x] - GPU - OpenCL Flow
* [x] - GPU - HIP Flow

### Missing functions in the implementation
* [ ] - vxRegisterUserStructWithName
* [ ] - vxGetUserStructNameByEnum
* [ ] - vxGetUserStructEnumByName
* [ ] - vxQueryMetaFormatAttribute

**Comment by kiritigowda** [comment]
#232 will add support to VX Vision Conformance

**Comment by kiritigowda** [comment]
#372 for Vision Conformance Profile

**Comment by kiritigowda** [comment]
@paveltc 

- [ ] RunVX support for 1.3 branch merging to master

**Comment by kiritigowda** [comment]
@paveltc any updates on RunVX support for threshold?

**Comment by paveltc** [comment]
@kiritigowda not yet. I need to take another look at it and possibly discuss it with you.

**Comment by kiritigowda** [comment]
* OpenVX CPU - Vision Feature Set Full Support
  + @paveltc can you benchmark these nodes with 1080P- [Nodes List](https://www.khronos.org/registry/OpenVX/specs/1.3/vx_khr_feature_sets/1.1/html/vx_khr_feature_sets_1_1.html#_vision_function_requirements)
  + Conformance run - `AGO_DEFAULT_TARGET=CPU LD_LIBRARY_PATH=./lib ./bin/vx_test_conformance`

* OpenVX GPU - OpenCL Vision Feature Set
  + Conformance run - `AGO_DEFAULT_TARGET=GPU LD_LIBRARY_PATH=./lib ./bin/vx_test_conformance --filter=-HarrisCorners.*:-*.ReplicateNode:-*.ImageContainmentRelationship:-*.OnRandomAndNatural:-*.vxWeightedAverage:-vxCanny.*:-*.MapRandomRemap:*.*`

* OpenVX GPU - HIP Vision Feature Set
  + Conformance run - @asalmanp can you put the passing run filter here

**Comment by asalmanp** [comment]
@kiritigowda this the passing run filter for HIP backend
LD_LIBRARY_PATH=./lib ./bin/vx_test_conformance --filter=-*.VirtualArray:-FastCorners.*:-HarrisCorners.*:-vxCanny.*:-*.ReplicateNode:-*.ImageContainmentRelationship:-*.GraphState:-*.MapRandomRemap:-*.OnRandomAndNatural:-*.vxWeightedAverage:-Convolve.GraphProcessing:-Gaussian3x3.GraphProcessing:-Scale.GraphProcessing:-WarpPerspective.GraphProcessing:-Remap.GraphProcessing:-GaussianPyramid.GraphProcessing:-HalfScaleGaussian.GraphProcessing:*.*

**Comment by kiritigowda** [comment]
@asalmanp can you give me the missing lib needed to build HIP conformance?
```
cmake -DOPENVX_INCLUDES=\$OPENVX_INC/include -DOPENVX_LIBRARIES=\$OPENVX_DIR/lib/libopenvx.so\\;\$OPENVX_DIR/lib/libvxu.so\\;pthread\\;dl\\;m\\;rt -DOPENVX_CONFORMANCE_VISION=ON ../OpenVX-cts
```

**Comment by asalmanp** [comment]
@kiritigowda please see below. The bold text is the required libs for building HIP conformance.

cmake -DCMAKE_BUILD_TYPE=Debug -DOPENVX_INCLUDES=$OPENVX_INC/include -DOPENVX_LIBRARIES=$OPENVX_DIR/lib/libopenvx.so\**;$OPENVX_DIR/lib/libopenvx_hip.so\;/opt/rocm/hip/lib/libamdhip64.so\;**pthread\;dl\;m\;rt -DOPENVX_CONFORMANCE_VISION=ON ../OpenVX-cts

**Comment by kiritigowda** [comment]
OpenVX 1.3 CPU/GPU - OpenCL/HIP support added to TOT. New Issue to track conformance to be Opened.
