### ISSUE TITLE
Protobuf V-3.12.0 Support

### ISSUE THREAD

**Issue by kiritigowda** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#287]
* The current version installed by MIVisionX-setup is [Protobuf - V3.5.2](https://github.com/protocolbuffers/protobuf/releases/tag/v3.5.2)

* Need to update this to [V-3.11.4](https://github.com/protocolbuffers/protobuf/releases/tag/v3.11.4)

* Build and tests needs to be verified.

* Update all dockers with latest changes

**Comment by paveltc** [comment]
@kiritigowda Should I install it manually or run MIVisionX-setup.py?

**Comment by LakshmiKumar23** [comment]
@paveltc I tried to install manually from [github ](https://github.com/linux-on-ibm-z/docs/wiki/Building-ProtoBuf-3.x#step-3-build-and-install)directly. And built it. Steps 3 onwards

**Comment by kiritigowda** [comment]
Need to updates setup script 

* change version to 3.11.4
```
	os.system('(cd '+deps_dir+'; wget https://github.com/protocolbuffers/protobuf/archive/v3.5.2.zip )')
	os.system('(cd '+deps_dir+'; unzip v3.5.2.zip )')
```

* change folder name to 3.11.4

```
# Install ProtoBuf
	os.system('sudo -v')
	os.system('(cd '+deps_dir+'/protobuf-3.5.2; sudo '+linuxFlag+' '+linuxSystemInstall+' -y '+linuxSystemInstall_check+' install autoconf automake libtool curl make g++ unzip )')
	os.system('sudo -v')
	os.system('(cd '+deps_dir+'/protobuf-3.5.2; sudo '+linuxFlag+' '+linuxSystemInstall+' autoremove )')
	os.system('(cd '+deps_dir+'/protobuf-3.5.2; ./autogen.sh )')
	os.system('(cd '+deps_dir+'/protobuf-3.5.2; ./configure )')
	os.system('(cd '+deps_dir+'/protobuf-3.5.2; make -j8 )')
	os.system('(cd '+deps_dir+'/protobuf-3.5.2; make check -j8 )')
	os.system('sudo -v')
	os.system('(cd '+deps_dir+'/protobuf-3.5.2; sudo '+linuxFlag+' make install )')
	os.system('sudo -v')
	os.system('(cd '+deps_dir+'/protobuf-3.5.2; sudo '+linuxFlag+' ldconfig )')
	os.system('sudo -v')
	os.system('(cd '+deps_dir+'/protobuf-3.5.2; sudo '+linuxFlag+' '+linuxSystemInstall+' -y '+linuxSystemInstall_check+' install python-pip )')
	os.system('sudo -v')
```

**Comment by paveltc** [comment]
@kiritigowda I ran a smoke test and it seems that this version of Protobuf works fine. Perhaps we can discuss more extensive testing offline.

**Comment by kiritigowda** [comment]
@rrawther should be upgrade to 3.11.4 or 3.12, can we check with MCW.

**Comment by rrawther** [comment]
Yes. Please upgrade to 3.12

**Comment by kiritigowda** [comment]
@paveltc can we rerun all the tests with V-3.12.0 - https://github.com/protocolbuffers/protobuf/releases/tag/v3.12.0, I am making changes to the setup to allow for version specification

**Comment by paveltc** [comment]
@kiritigowda I'll run the tests and let you know.

**Comment by kiritigowda** [comment]
@paveltc is this good to go?

**Comment by paveltc** [comment]
@kiritigowda Yes, it's good to go.

**Comment by kiritigowda** [comment]
PR - #322 fixes this issue.

**Comment by kiritigowda** [comment]
#322 merged
