### ISSUE TITLE
MIVisionX-setup.py: git submodule update not needed

### ISSUE THREAD

**Issue by jlgreathouse** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#3]
In MIVisionX-setup.py, [line 103](https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/blob/1.0.0/MIVisionX-setup.py#L103) attempts to perform a `git submodule update --init --recursive` in the `protobuf-3.5.2` folder. However, this folder comes from a release .zip file, rather than from a `git clone`. As such, it is not a git repository (it has no `.git` folder).

When I try to run this script, it shows the following error:
`fatal: Not a git repository (or any of the parent directories): .git`

It then goes on because the script does not error checking. I believe the solution here is to simply not include line 110. Thoughts?

**Comment by kiritigowda** [comment]
@jlgreathouse thanks for catching this. This line was used when the master branch of protobuf was cloned. If you have removed this line in your fork, please send me a pull request, else I can remove this line.

**Comment by kiritigowda** [comment]
PR #6 fixes this error.
