### ISSUE TITLE
MIVisionX - Python3 Support 

### ISSUE THREAD

**Issue by kiritigowda** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#326]
Ubuntu 18.04 and above with the latest update and upgrade will not support python2.

Support all existing python scripts with python3.

**Comment by kiritigowda** [comment]
@hansely & @LakshmiKumar23 - with PR #380 we need to verify that all the python scripts in the repo work with Python3 and pip3 packages. We can close all the issues together

- [  ] : Model Compiler Python3 Support Verification
- [  ] : Setup Script install PIP3 packages
- [  ] : Samples - inference examples to use python3
- [  ] : Update all apps and utilities to use python3 complaint model compiler.

**Comment by kiritigowda** [comment]
@LakshmiKumar23 can you verify that all the modules are python3 ready?

**Comment by LakshmiKumar23** [comment]
@kiritigowda Model compiler and setup script is python3 complaint. We haven't worked on the apps yet

**Comment by kiritigowda** [comment]
@LakshmiKumar23 & @hansely close/let me know about this issue when apps are updated.

**Comment by kiritigowda** [comment]
@LakshmiKumar23 are the apps updated?

**Comment by LakshmiKumar23** [comment]
> @LakshmiKumar23 are the apps updated?

@kiritigowda Cannot update validation toolkit till rali_pybind is updated

**Comment by kiritigowda** [comment]
@LakshmiKumar23 any updates on this?

**Comment by kiritigowda** [comment]
> @LakshmiKumar23 any updates on this?


@LakshmiKumar23 are there any scripts in TOT that do not support python3?

**Comment by LakshmiKumar23** [comment]
> > @LakshmiKumar23 any updates on this?
> 
> @LakshmiKumar23 are there any scripts in TOT that do not support python3?

@kiritigowda The model compiler and setup is updated. Need to look into all the apps. Some of it haven't been updated I think. Plus the training app doesn't run on TOT master, because of changes in rocAL. But maybe that can be created as a separate issue for the rocAL apps, and I can check on the remaining apps

**Comment by kiritigowda** [comment]
@LakshmiKumar23 it would be better to have a new issue that is more targeted. I feel this issue is too generic. We can close this if you open a new one.

**Comment by LakshmiKumar23** [comment]
@kiritigowda Sounds good. I just went through our apps folder. Only the two listed below are python apps. The rest is c++

1.  [python_inference_analyzer](https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/tree/master/apps/mivisionx_inference_analyzer)  already supports Python3
2. [mivisionx_validation_toolkit](https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/tree/master/apps/mivisionx_validation_tool) needs the new rocAL python interface.

Can close this issue.
