### ISSUE TITLE
OpenVX Core - vxChannelCombineNode corrupting images

### ISSUE THREAD

**Issue by wsphillips** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#338]
There appears to be an issue with graphs that use the channel combine node. Resulting RGB images have periodic artifacts.
![airplane_test](https://user-images.githubusercontent.com/27030706/87884196-fc53f380-ca0c-11ea-8346-95c77f76ffd0.jpg)

I ran into this issue when using the [filter code example](https://github.com/rgiduthuri/openvx_tutorial/blob/master/book_samples/filter/filterImage.c) from the official OpenVX Programming Guide. (i.e. it can be used as a reproducer)

Removing the convolution/filter nodes from the above example and creating a graph that only does a RGB channel extract to 3 virtual U8 images and recombining to an RGB output image is enough to trigger the bug. 

The `canny` example from this repo does _not_ cause a problem either (therefore unlikely that split channel data is corrupted during extraction).

Manually recreating the graph pipeline with immediate mode functions (e.g. `vxuChannelCombine`) does NOT result in corrupted images--resulting RGB composites are fine.

This was run on CentOS 8.1 / ROCm 3.5.1 using `mivisionx` AMD repo binaries (and also building from `master` to be sure). (GPU is gfx906 -- Radeon VII)

**Comment by kiritigowda** [comment]
# Test

GDF - [channelCombineRGB.txt](https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/files/5389509/channelCombineRGB.txt)

run sample
* Test CPU Flow
```
runvx -affinity:cpu channelCombineRGB.txt
```
* Test GPU Flow
```
runvx -affinity:gpu channelCombineRGB.txt
```

Test Package - [channelCombineRGB.zip](https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/files/5389526/channelCombineRGB.zip)

**Comment by kiritigowda** [comment]
@LakshmiKumar23 - attached is the OpenCL code & out.rgb (480x360) generated for the above graph for reference - [cl-buffer.zip](https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/files/5405797/cl-buffer.zip)

**Comment by LakshmiKumar23** [comment]
@kiritigowda I don't see this issue on windows. Also, in attached OpenCL code, lines 14&15 redefine uint8.

**Comment by kiritigowda** [comment]
> # Test
> GDF - [channelCombineRGB.txt](https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/files/5389509/channelCombineRGB.txt)
> 
> run sample
> 
> * Test CPU Flow
> 
> ```
> runvx -affinity:cpu channelCombineRGB.txt
> ```
> 
> * Test GPU Flow
> 
> ```
> runvx -affinity:gpu channelCombineRGB.txt
> ```
> 
> Test Package - [channelCombineRGB.zip](https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/files/5389526/channelCombineRGB.zip)

@hansely can you try this test case and verify the issue is fixed?

**Comment by hansely** [comment]
@kiritigowda The channel combine is fixed.  However, the problem still remains due to channel extract issue. I am working on the fix for it.
