### ISSUE TITLE
ADAT - Improvements and Bug Fixes

### ISSUE THREAD

**Issue by kiritigowda** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#378]
- [x] - **Hierarchy:** make optional 
- [x] - **Images:** paging to reduce load time
- [x] - **Images:** fix filters
- [ ] - **Images:** add hierarchy info - optional
- [x] - **Labels:** fix discrepancies in totals
- [x] - **Labels:** link to images filter
- [ ] - **Compare:** check database or model variations before adding to page

**Comment by kiritigowda** [comment]
@bijayraj list of ADAT bugs/improvement above add additional if missing

**Comment by kiritigowda** [comment]
@bijayraj for the PR #386 needs a couple of fixes before the merge. Can you look at? Thanks!

**Comment by bijayraj** [comment]
> @bijayraj for the PR #386 needs a couple of fixes before the merge. Can you look at? Thanks!

New commits were made to address the issues! 
All codes are now compatible with Python 2.7.

**Comment by kiritigowda** [comment]
ADAT improvements merged with master #386
