### ISSUE TITLE
Neural Net - Does MIVision support APU integrated GPUs in AMD APUs

### ISSUE THREAD

**Issue by ouyangjai** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#398]
Have a device AMD Ryzen 4650U, does MIVisionX support inference on integrated GPU?

**Comment by kiritigowda** [comment]
@ouyangjai MIVisionX Inference is currently supported on [ROCm supported hardware](https://github.com/RadeonOpenCompute/ROCm#hardware-and-software-support). 

We have not tested on 4650U, you could try Installation on supported linux distribution with your machine.

**Comment by ouyangjai** [comment]
@kiritigowda Thanks for your prompt response, do you test any APU with MVisionX, from  ROCm supported hardware page.
it states that "The integrated GPUs in AMD APUs are not officially supported targets for ROCm", but some of the APUs are enabled with OpenCL runtime, it is a kind of confusing.

**Comment by kiritigowda** [comment]
@ouyangjai I tried inference on AMD APU using MIVisionX 

APU - `AMD Ryzen Embedded V1605B with Radeon Vega Gfx`

```
inceptionv4 - Batch size 1
OK: loaded 37 kernels from libvx_nn.so
OK: OpenVX using GPU device#0 (gfx902+xnack) [OpenCL 2.0 ] [SvmCaps 0 0]
OK: graph initialization with annAddToGraph() took 245276.938 msec
OK: vxProcessGraph() took 8899.835 msec (1st iteration)
OK: vxProcessGraph() took 266.969 msec (average over 100 iterations)
OK: OpenCL buffer usage: 194250988, 757/757
OK: successful
```

To setup, your system for MIVisionX use the following

* Ubuntu 18.04
* ROCm 3.10 
* BIOS option - enable IOMMU
* Use MIVisionX-setup.py to install all deps - use `--rali no`
* Build and install MIVisionX
* Use Model Compiler to convert the model and run

**Comment by kiritigowda** [comment]
Reopening this issue to document MIVisionX Neural Net Flow on WIKI

**Comment by ouyangjai** [comment]
Thanks for the update, i am also able to run MIVisionx on Rayzen 5 4650g

./classifier --mode 1 --image ../MIVisionX-Inference-Tutorial/data/images/img_05.JPG --model_weights ../model/squeezenet/squeezenet-openvx/weights.bin --label ../MIVisionX-Inference-Tutorial/data/sample_classification_labels.txt --model_input_dims 3,224,224 --model_output_dims 1000,1,1 --model_name SqueezeNet_ONNX
OK: loaded 37 kernels from libvx_nn.so
OK: OpenVX using GPU device#0 (gfx902) [OpenCL 2.0 ] [SvmCaps 0 0]
MIOpen(OpenCL): Warning [ParseAndLoadDb] File is unreadable: /opt/rocm-3.9.0/miopen/share/miopen/db/gfx902_27.OpenCL.fdb.txt
OK: graph initialization with annAddToGraph() took 22307.730 msec
OK: vxProcessGraph() took 1246.389 msec (1st iteration)
OK: NN Model took 4.374 msec (average over 100 iterations)

**Comment by kiritigowda** [comment]
> Thanks for the update, i am also able to run MIVisionx on Rayzen 5 4650g
> 
> ./classifier --mode 1 --image ../MIVisionX-Inference-Tutorial/data/images/img_05.JPG --model_weights ../model/squeezenet/squeezenet-openvx/weights.bin --label ../MIVisionX-Inference-Tutorial/data/sample_classification_labels.txt --model_input_dims 3,224,224 --model_output_dims 1000,1,1 --model_name SqueezeNet_ONNX
> OK: loaded 37 kernels from libvx_nn.so
> OK: OpenVX using GPU device#0 (gfx902) [OpenCL 2.0 ] [SvmCaps 0 0]
> MIOpen(OpenCL): Warning [ParseAndLoadDb] File is unreadable: /opt/rocm-3.9.0/miopen/share/miopen/db/gfx902_27.OpenCL.fdb.txt
> OK: graph initialization with annAddToGraph() took 22307.730 msec
> OK: vxProcessGraph() took 1246.389 msec (1st iteration)
> OK: NN Model took 4.374 msec (average over 100 iterations)

@ouyangjai did you have to change any bios settings with your system or it came preset?

**Comment by kiritigowda** [comment]
@paveltc we need to add v1000 into the pipeline

**Comment by kiritigowda** [comment]
@ouyangjai any updates on the bios setting?

I have compiled a full instruction to enable MIVisionX on APU for computer vision and machine learning inference - https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/wiki/MIVisionX-Inference-on-AMD-Accelerated-Processing-Unit-(APU)

Closing this issue, use the [wiki page](https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/wiki/MIVisionX-Inference-on-AMD-Accelerated-Processing-Unit-(APU)) for steps to install MIVisionX on APUs.
