### ISSUE TITLE
Neural Net - FP16 Flow

### ISSUE THREAD

**Issue by kiritigowda** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#399]
# Model Conversion
* No know model conversion error  

# Model Accuracy 
* [ ] - VGG16 - Exhibits errors in FP16 mode
* [ ] - VGG19 - Exhibits errors in FP16 mode

# Model Performance
* No know model performance decay

@paveltc and @LakshmiKumar23 let's use this issue to track any FP16 accuracy loss or errors

**Comment by kiritigowda** [comment]
@LakshmiKumar23 can look into this below issue 

```
  File "/opt/rocm/mivisionx/model_compiler/python/nnir_to_openvx.py", line 1642
    elif input_data_type == "F016":
                                  ^
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by LakshmiKumar23** [comment]
> @LakshmiKumar23 can look into this below issue
> 
> ```
>   File "/opt/rocm/mivisionx/model_compiler/python/nnir_to_openvx.py", line 1642
>     elif input_data_type == "F016":
>                                   ^
> TabError: inconsistent use of tabs and spaces in indentation
> ```

@kiritigowda This error popped up when I was testing, but I commited a fix for this the in PR #404

**Comment by kiritigowda** [comment]
#429 - Linking FP16 Errors

**Comment by kiritigowda** [comment]
@paveltc can we track this issue? Maybe fixed on TOT.

**Comment by kiritigowda** [comment]
@paveltc can you verify this is fixed with TOT?

**Comment by paveltc** [comment]
@kiritigowda I'll take a look at it this week sometime. Is this Caffe? ONNX?
As far as I know, this has been fixed for a while but I will run the tests again when I get a chance.

**Comment by kiritigowda** [comment]
> @kiritigowda I'll take a look at it this week sometime. Is this Caffe? ONNX?
> As far as I know, this has been fixed for a while but I will run the tests again when I get a chance.

It's for the caffe flow

**Comment by kiritigowda** [comment]
Closing this issue as FP16 issues not found.
