### ISSUE TITLE
Neural Net - MIVisionX/samples/model_compiler_samples, Sample 3 - Classification Using Pre-Trained NNEF Model not working properly

### ISSUE THREAD

**Issue by Mark3452** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#405]
I've been having an issue where I can't Sample 3 working for the compiler samples, I've set it up according to the steps https://gpuopen-professionalcompute-libraries.github.io/MIVisionX/samples/model_compiler_samples/#sample-3---classification-using-pre-trained-nnef-model, the full steps i used are listed bellow.

About half the time I run the classifier it will report unclassified. I will re-run it with exact same arguments and input image and some times it will classify and some times not.

When the images do classify they done seem correct. Image 01 classifies as  minivan (the image is a minicopper), image 02 classifies as a pole (the image is a car), image 03 has never classified, neither has 04, and 05 classifies as a schipperke (the image is a cat).

I have tried running sample-2 and it seems to work properly.

Here are the steps I used to setup sample 3:

![image](https://user-images.githubusercontent.com/75698296/101540194-a78a2880-396d-11eb-8c29-4b0803966779.png)

I haven't tried using the docker image yet, I will try it soon and post any updates here.

Any help would be appreciated!

Thanks,
Mark

**Comment by kiritigowda** [comment]
@Mark3452 I can take a look at this.

But just as a side note, the models in the NNEF model zoo are not claiming accuracy, we don't know if these models are fully trained. You could try the sample 4 VGG-16 CAFFE model flow, as this model is known to have been trained well, you can also convert this caffe model to NNEF, using NNEF tools, if you need an NNEF flow which is accurate.

Let me know if you have the same problems with sample 4 - VGG16 CAFFE flow.

I will also try the NNEF model and verify the results.

**Comment by kiritigowda** [comment]
@hansely can you check the NNEF flow mentioned in this issue?

**Comment by Mark3452** [comment]
Hi @kiritigowda,

Thanks for the fast response!

When running sample-4 i'm getting the following issue when trying to convert the caffe model to NNIR: 

```
mark@sales:~/sample-4$ python /opt/rocm/mivisionx/model_compiler/python/caffe_to_nnir.py VGG_ILSVRC_16_layers.caffemodel vgg16
-nnir --input-dims 1,3,224,224
OK: loading caffemodel from VGG_ILSVRC_16_layers.caffemodel ...
OK: caffemodel read successful
converting to AMD NNIR format in vgg16-nnir folder ...
Killed
mark@sales:~/sample-4$
```

I will pause for about a second on "converting to AMD NNIR format in vgg16-nnir folder ..." and then say "killed"

I've also tried converting the VGG_16 caffe model listed here https://github.com/KhronosGroup/NNEF-Tools/tree/master/models, (the VGG_16 onnx->nnef model listed is the one used in sample-3) using the NNEF-Tools converter. The conversion seems to work fine and i'm able to build the classifier, but when I go to run it I get

```
mark@sales:~/caffe_to_nnef/build$ ./classifier --mode 1 --video ../MIVisionX-Inference-Tutorial/data/images/img_01.JPG --model_weights ../vgg16-openvx/weights.bin --label ../MIVisionX-Inference-Tutorial/data/sample_classification_labels.txt --model_input_dims 3,224,224 --model_output_dims 1000,1,1 --model_name VGG16_NNEF
OK: loaded 37 kernels from libvx_nn.so
ERROR: validate: conv: input[1x3x224x224] weights[96x3x11x11] output[10x96x55x55]
ERROR: agoVerifyGraph: kernel org.khronos.nn_extension.convolution_layer: kernel_validate failed (-15)
ERROR: Model vxVerifyGraph(...) failed (-15)
mark@sales:~/caffe_to_nnef/build$
```
I assumed these were the same models and thus i could you the dimensions from sample-3, but it would look like thats not the case, so ill try and find what the dimensions are.

I've also tried converting the caffe model from sample-4 to nnef using NNEF-Tools and I get
```
mark@sales:~/caffe_to_nnef$ python3 -m nnef_tools.convert --input-format caffe --output-format nnef --input-model ~/caffe_to_nnef/vgg16-caffe/VGG_ILSVRC_16_layers.prototxt --output-model ~/caffe_to_nnef/VGG_ILSVRC_16_layers.nnef
[W CUDAFunctions.cpp:100] Warning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (function operator())
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/nnef_tools-1.0-py3.6.egg/nnef_tools/convert.py", line 378, in <module>
  File "/usr/local/lib/python3.6/dist-packages/nnef_tools-1.0-py3.6.egg/nnef_tools/convert.py", line 270, in main
  File "/usr/local/lib/python3.6/dist-packages/nnef_tools-1.0-py3.6.egg/nnef_tools/io/caffe2/reader.py", line 139, in __call__
  File "/usr/local/lib/python3.6/dist-packages/nnef_tools-1.0-py3.6.egg/nnef_tools/io/caffe2/reader.py", line 107, in load_caffe_model_as_onnx
  File "/usr/local/lib/python3.6/dist-packages/nnef_tools-1.0-py3.6.egg/nnef_tools/io/caffe2/reader.py", line 39, in _caffe_to_caffe2
IndexError: list index (0) out of range
mark@sales:~/caffe_to_nnef$
```
There was no .prototxt included with the download link in sample-4, but im pretty sure the one I found at https://www.floydhub.com/floydhub/datasets/vgg-ilsvrc-16-layers/1 is the correct one for this model.


If you have any insight into waht could be casuing some thee issues it would be much appreciated!

Thanks,
Mark

**Comment by kiritigowda** [comment]
@Mark3452 - 

*  The conversion from caffe to AMD NNIR - will take some time as this model which is 0.5GB, see below, I will see if we can speed up this process or something is slowing it down.

```
python /opt/rocm/mivisionx/model_compiler/python/caffe_to_nnir.py VGG_ILSVRC_16_layers.caffemodel vgg16-nnir --input-dims 1,3,224,224
OK: loading caffemodel from VGG_ILSVRC_16_layers.caffemodel ...
OK: caffemodel read successful
converting to AMD NNIR format in vgg16-nnir folder ... 
OK: creating IR description in vgg16-nnir/graph.nnir ...
OK: creating IR binaries in vgg16-nnir/binary ...
OK: graph successfully formed.
```

* We are currently verifying the NNEF flow. Model accuracy is something we do not control, it depends on how the model was trained and how well it was trained.

**Comment by hansely** [comment]
@Mark3452 

1. caffe to nnir conversion
I was also able to convert the model with some waiting. Since the model is 0.5GB, it will take some time to convert the model depending on the cpu/gpu you are using.

2. The unclassified images in sample-3
As kiriti mentioned, these pre-trained models offered by NNEF are not very accurate. 
If you see image02 you'll see a pole behind the car. I'm assuming that's the reason why the classifier showed pole for image02. 
On my system, the image03 shows as tricycle which seems to be right.
For other images that show 'unclassified', you may try lowering the confidence level. The default confidence(threshold) value is set to 50.0. You can lower this by dragging the confidence bar to the left in the gui.

**Comment by hansely** [comment]
3. The caffemodel for vgg16
The pre-trained caffemodels in NNEF-zoo are all trained for batch size of 10.
That's why you are getting the following input/output dimension mismatch error.
``
validate: conv: input[1x3x224x224] weights[96x3x11x11] output[10x96x55x55]
``
Since they are not trained for single image, you'll have to update the batch size using nnir_update.py script.
Here is the example of updating the batch size with vgg16 caffemodel given in NNEF zoo.

```
mkdir vgg16-caffe && cd vgg16-caffe
wget https://sfo2.digitaloceanspaces.com/nnef-public/vgg16.caffemodel.nnef.tgz 
tar -xvf vgg16.caffemodel.nnef.tgz
cd ../
python /opt/rocm/mivisionx/model_compiler/python/nnef_to_nnir.py vgg16-caffe vgg16-nnir
python /opt/rocm/mivisionx/model_compiler/python/nnir_update.py --batch-size 1 vgg16-nnir vgg16-nnir-update
python /opt/rocm/mivisionx/model_compiler/python/nnir_to_openvx.py vgg16-nnir-update vgg16-openvx
```
The rest part would be the same as sample-3. 
I tried the model on my system but the accuracy was not quite good.
Hope this helps!

**Comment by kiritigowda** [comment]
@Mark3452 any updates on this issue?

I will close this issue. If you still need further clarification or need to install this on [APU](https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/wiki/MIVisionX-Inference-on-AMD-Accelerated-Processing-Unit-(APU)) please reopen this issue.

**Comment by Mark3452** [comment]
Thanks for the clarification about the vgg16 model's accuracy. It might be worth it too add a note to the setup guide explaining that the models are not accurate, because I would imagine that other people could also assume that they had not set it up right when they see the poor performance.


As for the caffe to nnir conversion, I was able to get it working by changing the convert_caffe_to_ir_bin function in caffe_to_nnir.py to

```
# convert caffe bin formats to ir bin formats.
def convert_caffe_bin_to_ir_bin(floatlist):
    print(floatlist[0], floatlist[-1])
    if (len(floatlist) == 102760448):
        buf = struct.pack('%sf' % str(30000000), *(floatlist[0:30000000]))
        buf += struct.pack('%sf' % str(30000000), *(floatlist[30000000:60000000]))
        buf += struct.pack('%sf' % str(30000000), *(floatlist[60000000:90000000]))
        buf += struct.pack('%sf' % str(12760448), *(floatlist[90000000:120000000]))
    else:
        buf = struct.pack('%sf' % str(len(floatlist)), *floatlist)
    return buf
```

Its seems that on my system it would crash if it was trying to pack to much data at once so just splitting it up into four calls seemed to make it work.

Thanks you @kiritigowda and @hansely for all your help!
