### ISSUE TITLE
RALI - rali_pybind not installing on Pytorch docker

### ISSUE THREAD

**Issue by rrawther** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#425]
rali_pybind distribution package is not installing when using ./run.sh in recent ROCm pytorch docker. 
I think it is installing in a different path than /opt/conda/lib/python3.6...

**Comment by rrawther** [comment]
@shobana-mcw @Indumathi31: Can you please take a look at this issue. I have experienced this while debugging training.

**Comment by rrawther** [comment]
@LakshmiKumar23 : Can you please work with @shobana-mcw to resolve this issue as soon as possible since it affects all our training scripts.

**Comment by kiritigowda** [comment]
@shobana-mcw any update on this issue?

**Comment by shobana-mcw** [comment]
We have to install using the command setup.py install instead of run.sh for conda environments. This has been conveyed to Rajy.

**Comment by kiritigowda** [comment]
@LakshmiKumar23 can we make a note of this and close this issue?

> We have to install using the command setup.py install instead of run.sh for conda environments. This has been conveyed to Rajy.

@LakshmiKumar23 can we make a note of this and close this issue?

**Comment by LakshmiKumar23** [comment]
> @LakshmiKumar23 can we make a note of this and close this issue?
> 
> > We have to install using the command setup.py install instead of run.sh for conda environments. This has been conveyed to Rajy.

@kiritigowda Sure, I can update the README
