### ISSUE TITLE
Model Compiler - ONNX to NNIR Failure

### ISSUE THREAD

**Issue by kiritigowda** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#428]
Failure to convert ONNX to NNIR

```
python3 /opt/rocm/mivisionx/model_compiler/python/onnx_to_nnir.py squeezenet1.0-8.onnx test
loading ONNX model from squeezenet1.0-8.onnx ...
Traceback (most recent call last):
  File "/opt/rocm/mivisionx/model_compiler/python/onnx_to_nnir.py", line 262, in <module>
    main()
  File "/opt/rocm/mivisionx/model_compiler/python/onnx_to_nnir.py", line 257, in main
    onnx_model_proto.ParseFromString(open(onnxFileName, 'rb').read())
google.protobuf.message.DecodeError: Error parsing message
```

**Comment by kiritigowda** [comment]
Tests - https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/tree/master/tests/neural_network_tests#mivisionx-neural-network-tests

**Comment by LakshmiKumar23** [comment]
@kiritigowda Turns out the model is not valid. Please use the below to check. We need to swap out all models like this with those that are valid
```
import sys
import onnx
onnx.checker.check_model(onnx.load("<PATH_TO_ONNX_MODEL>"))
```

This throws an error with all the mnist models available in the [model zoo](https://github.com/onnx/models/tree/master/vision/classification/mnist)

**Comment by LakshmiKumar23** [comment]
@kiritigowda The issue is you cannot download the model from model zoo ONNX with wget. The download doesn't get complete fully. I downloaded onto my windows system and copied the whole 5MB file (in case of squeezenet) to my ubuntu system. Found this out while debugging some stuff for @paveltc. Closing this issue. MNIST doesn't throw the protobuf error either.

``` 
python3 onnx_to_nnir.py ~/onnxModels/squeezenet1.0-8.onnx ../../py3_squeezenet_onnx_ir
loading ONNX model from /home/svcbuild/onnxModels/squeezenet1.0-8.onnx ...
converting to IR model in ../../py3_squeezenet_onnx_ir ...
OK: creating IR description in ../../py3_squeezenet_onnx_ir/graph.nnir ...
OK: creating IR binaries in ../../py3_squeezenet_onnx_ir/binary ...
svcbuild@ThreadRipperUbuntu:~/work/lk/MIVisionX/model_compiler/python$ python3 nnir_to_openvx.py ../../py3_squeezenet_onnx_ir/ ../../py3_squeezenet_onnx_ovx
reading IR model from ../../py3_squeezenet_onnx_ir/ ...
OK: reading IR description from ../../py3_squeezenet_onnx_ir//graph.nnir ...
OK: reading IR binaries from ../../py3_squeezenet_onnx_ir//binary ...
#OUTPUT-TENSOR: softmaxout_1 1 1000 1 1
creating C code in ../../py3_squeezenet_onnx_ovx ...
creating ../../py3_squeezenet_onnx_ovx/CMakeLists.txt ...
creating ../../py3_squeezenet_onnx_ovx/cmake/FindOpenCL.cmake ...
creating ../../py3_squeezenet_onnx_ovx/annmodule.h ...
creating ../../py3_squeezenet_onnx_ovx/annmodule.cpp ...
creating ../../py3_squeezenet_onnx_ovx/weights.bin ...
creating ../../py3_squeezenet_onnx_ovx/anntest.cpp ...
creating ../../py3_squeezenet_onnx_ovx/annpython.h ...
creating ../../py3_squeezenet_onnx_ovx/annpython.cpp ...
creating ../../py3_squeezenet_onnx_ovx/anntest.py ...
svcbuild@ThreadRipperUbuntu:~/work/lk/MIVisionX/model_compiler/python$ cd ../../py3_squeezenet_onnx_ovx/
svcbuild@ThreadRipperUbuntu:~/work/lk/MIVisionX/py3_squeezenet_onnx_ovx$ cmake .
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OPENCL: /opt/rocm/opencl/lib/libOpenCL.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/svcbuild/work/lk/MIVisionX/py3_squeezenet_onnx_ovx
svcbuild@ThreadRipperUbuntu:~/work/lk/MIVisionX/py3_squeezenet_onnx_ovx$ make
Scanning dependencies of target annmodule
[ 16%] Building CXX object CMakeFiles/annmodule.dir/annmodule.cpp.o
[ 33%] Linking CXX shared library libannmodule.so
[ 33%] Built target annmodule
Scanning dependencies of target annpython
[ 50%] Building CXX object CMakeFiles/annpython.dir/annpython.cpp.o
[ 66%] Linking CXX shared library libannpython.so
[ 66%] Built target annpython
Scanning dependencies of target anntest
[ 83%] Building CXX object CMakeFiles/anntest.dir/anntest.cpp.o
[100%] Linking CXX executable anntest
[100%] Built target anntest
svcbuild@ThreadRipperUbuntu:~/work/lk/MIVisionX/py3_squeezenet_onnx_ovx$ ./anntest weights.bin
OK: loaded 37 kernels from libvx_nn.so
OK: OpenVX using GPU device#0 (gfx906) [OpenCL 2.0 ] [SvmCaps 0 0]
OK: graph initialization with annAddToGraph() took 19864.164 msec
OK: vxProcessGraph() took 1107.634 msec (1st iteration)
OK: vxProcessGraph() took 1.406 msec (average over 100 iterations)
OK: OpenCL buffer usage: 14954048, 58/58
OK: successful
```

**Comment by LakshmiKumar23** [comment]
@kiritigowda Please close this issue

**Comment by kiritigowda** [comment]
@LakshmiKumar23 still having this issue on your system, using the model you suggested 

```
python3 /opt/rocm/mivisionx/model_compiler/python/onnx_to_nnir.py squeezenet1.0-8.onnx sqeezenet-nnir
loading ONNX model from squeezenet1.0-8.onnx ...
Traceback (most recent call last):
  File "/opt/rocm/mivisionx/model_compiler/python/onnx_to_nnir.py", line 262, in <module>
    main()
  File "/opt/rocm/mivisionx/model_compiler/python/onnx_to_nnir.py", line 257, in main
    onnx_model_proto.ParseFromString(open(onnxFileName, 'rb').read())
google.protobuf.message.DecodeError: Error parsing message

```

**Comment by kiritigowda** [comment]
ONNX flowing working - tested with runNeuralNetTest scripts.

### MODEL FORMAT: ONNX no fused OPs
|      Model Name      | Batch Size | Time/Batch (ms) | Time/Image (ms) |
|----------------------|------------|-----------------|-----------------|
|onnx-squeezenet       |1           |1.076            |1.076            |
|onnx-squeezenet       |2           |1.040            |0.520            |
|onnx-squeezenet       |4           |1.049            |0.262            |
|onnx-squeezenet       |8           |1.052            |0.132            |
|onnx-squeezenet       |16          |1.050            |0.066            |
|onnx-squeezenet       |32          |1.045            |0.033            |
|onnx-squeezenet       |64          |1.047            |0.016            |

### MODEL FORMAT: ONNX fused Ops
|      Model Name      | Batch Size | Time/Batch (ms) | Time/Image (ms) |
|----------------------|------------|-----------------|-----------------|
|onnx-squeezenet       |1           |1.106            |1.106            |
|onnx-squeezenet       |2           |1.098            |0.549            |
|onnx-squeezenet       |4           |1.100            |0.275            |
|onnx-squeezenet       |8           |1.093            |0.137            |
|onnx-squeezenet       |16          |1.100            |0.069            |
|onnx-squeezenet       |32          |1.096            |0.034            |
|onnx-squeezenet       |64          |1.092            |0.017            |

### MODEL FORMAT: ONNX fp16
|      Model Name      | Batch Size | Time/Batch (ms) | Time/Image (ms) |
|----------------------|------------|-----------------|-----------------|
|onnx-squeezenet       |1           |1.183            |1.183            |
|onnx-squeezenet       |2           |1.118            |0.559            |
|onnx-squeezenet       |4           |1.121            |0.280            |
|onnx-squeezenet       |8           |1.096            |0.137            |
|onnx-squeezenet       |16          |1.075            |0.067            |
|onnx-squeezenet       |32          |1.095            |0.034            |
|onnx-squeezenet       |64          |1.096            |0.017            |
