### ISSUE TITLE
RALI APP - Failure

### ISSUE THREAD

**Issue by rrawther** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#432]
This was not happening before. Need to do regression test. 
I have done some debugging and saw vxReleaseImage is where it is hanging.

**Comment by rrawther** [comment]
@paveltc Can you please double check if this is happening on the tot?

**Comment by kiritigowda** [comment]
@paveltc is this verified? can this bug be closed? @rrawther

**Comment by paveltc** [comment]
@kiritigowda Yes, this has been fixed.
