### ISSUE TITLE
Neural Net - inference model speed benchmarks for performance idea ?

### ISSUE THREAD

**Issue by hyperfraise** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#445]
Hi. I've stumbled upon this and it seems very interesting. I'm very eager to see benchmarks especially on AMD integrated GPUs coming with G series APUs. But also for regular discrete GPUs such as 5700XT etc...

Do you guys have benchmarks of model speed for common deep learning models such as resnet-50 ? I can't find any on the web.

Thank you.

**Comment by kiritigowda** [comment]
@hyperfraise our team does not publish the performance numbers to make available, but you can run the supported models on the supported hardware to get the performance numbers.

An example of how to run a model and list benchmark numbers is available in this [test script](https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/tree/master/tests/neural_network_tests#mivisionx-neural-network-tests)

**Comment by hyperfraise** [comment]
I don't have AMD IG.

So you're saying you're working on all of this, but you don't care that the public finds this useful, based on speed improvements ?

**Comment by kiritigowda** [comment]
> I don't have AMD IG.
> 
> So you're saying you're working on all of this, but you don't care that the public finds this useful, based on speed improvements ?

@hyperfraise our aim is definitely to provide our users with a useful library. As you can see that the full-stack codebase is open-sourced here on GitHub, generating useful metrics should be easy for the users. 

As there are no secret knobs to disable performance for paid/free users in the stack, the metrics should be the same for all.
