### ISSUE TITLE
Neural Net - ONNX model for object detection inference on Windows

### ISSUE THREAD

**Issue by gitLED** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#446]
Can I use the OnNX model for object detection inference in Win10?
I am confused. I see that it emphasizes that the support system does not include Windows.
The reason I want to use an AMD graphics card for deep learning reasoning is that I want to replace an NVIDIA graphics card.

![image](https://user-images.githubusercontent.com/76691514/110570787-764e0e00-8191-11eb-9d55-72684c347431.png)
![20210310112417](https://user-images.githubusercontent.com/76691514/110571855-3ab44380-8193-11eb-8923-d6f4f004d1db.png)
Can I use the OnNX model for object detection inference in Win10?

**Comment by kiritigowda** [comment]
@gitLED you can use the OpenVX [WinML extension](https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/tree/master/amd_openvx_extensions/amd_winml#amd-winml-extension) to run inference on Windows 10 with ONNX models. More info on how to build and run [here](https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/tree/master/amd_openvx_extensions/amd_winml#build-instructions)


![](https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/raw/master/docs/images/winmlRuntime.png)

**Comment by kiritigowda** [comment]
@gitLED were you able to use the instructions and run your model using WinML Ext?

**Comment by kiritigowda** [comment]
@gitLED reopen the issue if you need more info.
