### ISSUE TITLE
Which component is more recommendable between AMDMIgraphx and amd_nn in MIVisionx for inferencing

### ISSUE THREAD

**Issue by learner321** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#454]
I find that there is a MIGraphx project in ROCm repository.  And it also aims to inference in AI like amd_nn component in MIVisionx.  
What's the connection between these two components. Also for decoder and encoder, there is a AMF project like amd_media component in MIVisionx. It is a little confusing to me that why there are multiple components that do the same function for AMD card and how should I chose. Thank you :)

**Comment by rrawther** [comment]
MIGraphX is for running inference with onnx models on ROCm platform. 
MIVisionX is a CV-ML toolkit for computer vision and ML. amd_nn is OpenVX neural_network extension for inference deployment using OpenVX framework. AMF is for decoding and encoding input/output video/jpeg.
Currently they are two separate projects.  It depends on what you want to do? Please give some more details about your use case

**Comment by learner321** [comment]
Thanks for your reply. For our case, we want to do the video decoding and inferencing on AMD graphic card. However, we find that there are muilty components support these features, like amd_media and AMF support video decoding, amd_nn and migprahx support inferencing. So I am confused that which should I choose, like AMF for decoding and MIgraphx for inferencing or MIvision for decoding and MIvision for inferencing and other combinations. Also we find that MIVisonx, AMF, MIGraphx belong to different repositories, ROCm provides the deb packages of MIVisionx and MIgrahx.
