### ISSUE TITLE
OpenCV -  4.X support & updates

### ISSUE THREAD

**Issue by arpu** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#456]
Hey,
any Plans to use c++ only opencv 4.x.x ? 

i am on fedora and the distro package is 4.3.0-10.fc33

**Comment by kiritigowda** [comment]
@arpu are you looking at OpenCV Extension or all modules to be upgraded to OpenCV 4.X?

**Comment by arpu** [comment]
not sure i get some build errors with opencv4 in
```/home/arpu/Work/githubsources/MIVisionX_2021/utilities/runvx/vxUtils.h:82:10: schwerwiegender Fehler: opencv/cv.h: Datei oder Verzeichnis nicht gefunden
   82 | #include <opencv/cv.h>
``` 
for opencv4  we need

```
#include <opencv2/opencv.hpp>
#include <opencv2/highgui.hpp>

```

**Comment by kiritigowda** [comment]
@paveltc can we check if we can support RunVX with OpenCV 4.X?

**Comment by kiritigowda** [comment]
Support for OpenCV 4.X added with PR - #749

**Comment by kiritigowda** [comment]
OpenCV 4.X Support on TOT Master.
