### ISSUE TITLE
vxNormalizationLayer - fails during inference

### ISSUE THREAD

**Issue by LakshmiKumar23** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#460]
@kiritigowda  https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/blob/160765c28c7f4d400f2e233fd7c0c05458d93e97/amd_openvx/openvx/include/VX/vx_compatibility.h#L154

**Comment by kiritigowda** [comment]
Fix merged to TOT.
