### ISSUE TITLE
HIP - Vision Test Failure

### ISSUE THREAD

**Issue by kiritigowda** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#488]
RunVX fails to link with libopenvx.so, the exe in bin should not require .so's to be in the PATH.

Info - http://math-ci.rocm.amd.com/blue/organizations/jenkins/compute-rocm-dkms-no-npi-hipclang%2FShort-GPUOpen%2FMIVisionX/detail/PR-485/11/pipeline/491/

```
mivisionx/build/release-hip/bin/runvx: error while loading shared libraries: libopenvx.so: cannot open shared object file: No such file or directory
```

**Comment by asalmanp** [comment]
@kiritigowda I am not really sure if this is a bug. We would always need to set the LD_LIBRARY_PATH (e.g., export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/rocm/mivisionx/lib) before running the runvx. This is the case for all backends, CPU, OCL and HIP.

**Comment by kiritigowda** [comment]
Passing Vision Tests for HIP - http://math-ci.rocm.amd.com/blue/organizations/jenkins/compute-rocm-dkms-no-npi-hipclang%2FShort-GPUOpen%2FMIVisionX/detail/master/113/pipeline

Benchmark Report
--------

### Hardware: GPU

| OpenVX Node                          |Frames Count| tmp (ms) | avg (ms) | min (ms) | max (ms) |
|--------------------------------------|------------|----------|----------|----------|----------|
| AbsDiff_U8_U8U8                      |        100 |    0.286 |    0.331 |    0.285 |    4.787 |
