### ISSUE TITLE
MIVisionX-setup.py: passing sudo password on command-line is completely insecure

### ISSUE THREAD

**Issue by jlgreathouse** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#5]
Currently, the `MIVisionX-setup.py` script requires you pass your sudo password as the only required command-line flag. This is extremely bad practice, as it puts your (sudo-capable) password on your screen in plaintext, adds it to bash histories, etc. I'm raising this issue because there must be some other way of doing this.

For instance, if we just barrel through the script without trying to force the user's password to automatically be passed into `sudo`, it will at least prompt the user for the password in a non-logged prompt.

I assume this was avoided because you didn't want the install script to stall at another prompt at some later point in the installation process. If that is the case, there are [other potential solutions](https://serverfault.com/questions/266039/temporarily-increasing-sudos-timeout-for-the-duration-of-an-install-script). Or perhaps throwing `sudo -v` into the script at various points to refresh the sudo timeout.

In either case, I hope that the end solution is not to require users to use their password as a command-line parameter.

**Comment by kiritigowda** [comment]
@jlgreathouse Thanks for bringing this up. I have removed sudo requirement for the script. I will push the changes into the master.

**Comment by kiritigowda** [comment]
@jlgreathouse PR #6 addresses this issue.
