### ISSUE TITLE
Docker - rocAL_pybind install to  pytorch dockerfile

### ISSUE THREAD

**Issue by rrawther** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#537]

**Comment by kiritigowda** [comment]
with the TOT - pytorch dockerfile

`sudo docker build -f docker/pytorch/mivisionx-with-pytorch.dockerfile -t pytorch-mivisionx .`

```
-- Installing: /opt/rocm/mivisionx/lib/rali_pybind.cpython-36m-x86_64-linux-gnu.so
-- Set runtime path of "/opt/rocm/mivisionx/lib/rali_pybind.cpython-36m-x86_64-linux-gnu.so" to ""
Removing intermediate container 6620c2bb0588
 ---> 83647c2c5e6b
Successfully built 83647c2c5e6b
Successfully tagged pytorch-mivisionx:latest
```

@LakshmiKumar23 can you verify the install?

**Comment by kiritigowda** [comment]
@rrawther needs comprehensive changes to get rali renamed to rocAL completely.

* includes
* function name
* libs

**Comment by kiritigowda** [comment]
@LakshmiKumar23 closing this issue as we have the rocAL install on Docker. Reopen the issue if something is missing.
