### ISSUE TITLE
OpenVX Base - naming change for vx_kernel_attribute_amd_e

### ISSUE THREAD

**Issue by rrawther** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#538]
Need to change VX_KERNEL_ATTRIBUTE_AMD_OPENCL_BUFFER_ACCESS_ENABLE,
VX_KERNEL_ATTRIBUTE_AMD_OPENCL_BUFFER_UPDATE_CALLBACK and 
VX_KERNEL_ATTRIBUTE_AMD_OPENCL_GLOBAL_WORK_UPDATE_CALLBACK
to more generic names to be used for both HIP and OpenCL

**Comment by kiritigowda** [comment]
@asalmanp can you list all variables are used in HIP and any suggestions.

**Comment by asalmanp** [comment]
@kiritigowda we can use VX_KERNEL_ATTRIBUTE_AMD_GPU_BUFFER_ACCESS_ENABLE which is more generic for both backends. the other two variables are not used in HIP and they can stay unchanged.

**Comment by kiritigowda** [comment]
@asalmanp yes, we can go ahead with your suggestion. You can create a PR for this as all the old PR's have been merged.

**Comment by kiritigowda** [comment]
@rrawther can you review PR #548 to see if this solves this issue?

**Comment by kiritigowda** [comment]
PR #548 merged, please open new issue if changes required @rrawther
