### ISSUE TITLE
OpenVX - Warp Perspective Bilinear and Nearest Neighbor fails with OCL and HIP

### ISSUE THREAD

**Issue by paveltc** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#566]
The warp perspective kernel fails with bilinear and nearest neighbor parameters with OpenCL and HIP backends.
GDFs:
MIVisionX-tests/tree/master/openvx-test-suite/kernelGDFs/geometric-1280x720/WarpPerspective_U8_U8_Nearest.gdf
MIVisionX-tests/tree/master/openvx-test-suite/kernelGDFs/geometric-1280x720/WarpPerspective_U8_U8_Bilinear.gdf

**Comment by asalmanp** [comment]
> @asalmanp is this resolved?

@kiritigowda No, it's not fixed yet.

**Comment by kiritigowda** [comment]
Fixed with PR #620
