### ISSUE TITLE
mivisionx_openvx_classifier app build failure

### ISSUE THREAD

**Issue by anilmartha** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#577]
Followed the instructions from [here ](https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/tree/master/apps/mivisionx_openvx_classifier#build) using **mivisionx/ubuntu-18.04** docker. Seeing below error while building. 

**[ 25%] Building CXX object CMakeFiles/caffeModels.dir/source/caffeModels.cpp.o
/tmp/MIVisionX/apps/mivisionx_openvx_classifier/source/caffeModels.cpp: In function 'vx_status annAddToGraph_googleNet(vx_graph, vx_tensor, vx_tensor, vx_tensor, vx_tensor, const char*)':
/tmp/MIVisionX/apps/mivisionx_openvx_classifier/source/caffeModels.cpp:14566:22: error: 'vxNormalizationLayer' was not declared in this scope
     { vx_node node = vxNormalizationLayer(graph, max_pool_pool1_3x3_s2, VX_NN_NORMALIZATION_ACROSS_MAPS , 5, 1.000000e-04f, 7.500000e-01f, lrn_pool1_norm1);
                      ^~~~~~~~~~~~~~~~~~~~
/tmp/MIVisionX/apps/mivisionx_openvx_classifier/source/caffeModels.cpp:14566:22: note: suggested alternative: 'vxBatchNormalizationLayer'
     { vx_node node = vxNormalizationLayer(graph, max_pool_pool1_3x3_s2, VX_NN_NORMALIZATION_ACROSS_MAPS , 5, 1.000000e-04f, 7.500000e-01f, lrn_pool1_norm1);
                      ^~~~~~~~~~~~~~~~~~~~
                      vxBatchNormalizationLayer
/tmp/MIVisionX/apps/mivisionx_openvx_classifier/source/caffeModels.cpp:14607:22: error: 'vxNormalizationLayer' was not declared in this scope
     { vx_node node = vxNormalizationLayer(graph, relu_conv2_relu_3x3, VX_NN_NORMALIZATION_ACROSS_MAPS , 5, 1.000000e-04f, 7.500000e-01f, lrn_conv2_norm2);
                      ^~~~~~~~~~~~~~~~~~~~
/tmp/MIVisionX/apps/mivisionx_openvx_classifier/source/caffeModels.cpp:14607:22: note: suggested alternative: 'vxBatchNormalizationLayer'
     { vx_node node = vxNormalizationLayer(graph, relu_conv2_relu_3x3, VX_NN_NORMALIZATION_ACROSS_MAPS , 5, 1.000000e-04f, 7.500000e-01f, lrn_conv2_norm2);
                      ^~~~~~~~~~~~~~~~~~~~
                      vxBatchNormalizationLayer
CMakeFiles/caffeModels.dir/build.make:62: recipe for target 'CMakeFiles/caffeModels.dir/source/caffeModels.cpp.o' failed
make[2]: *** [CMakeFiles/caffeModels.dir/source/caffeModels.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/caffeModels.dir/all' failed
make[1]: *** [CMakeFiles/caffeModels.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2**

**Comment by LakshmiKumar23** [comment]
@kiritigowda I looked into this. It seems like OpenVX removed vxNormalizationLayer from it's support [here](https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/blob/master/amd_openvx/openvx/include/VX/vx_khr_nn.h) from version 1.3. Can you find out why this happened?

**Comment by kiritigowda** [comment]
@LakshmiKumar23 with 1.3 header updates, we moved batchNorm to  [vx_amd_nn.h](https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/blob/d4dfb0abab952fe9fc9a39df70106c36d5cc834d/amd_openvx_extensions/amd_nn/include/vx_amd_nn.h#L42) - we have to add vx_amd_nn.h to the application to fix this. I can add that.

**Comment by kiritigowda** [comment]
PR #582 fixes this issue. @anilmartha thanks for filing this issue. Please let us know if you have any other issues.

```
make
[ 25%] Building CXX object CMakeFiles/caffeModels.dir/source/caffeModels.cpp.o
[ 50%] Linking CXX shared library libcaffeModels.so
[ 50%] Built target caffeModels
[ 75%] Building CXX object CMakeFiles/classifier.dir/source/classifier.cpp.o
[100%] Linking CXX executable classifier
[100%] Built target classifier
```
