### ISSUE TITLE
Googlenet inference on fp16 fails in MIOpen fwd convolution call for fully connected layer

### ISSUE THREAD

**Issue by rrawther** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#58]
Steps to reproduce.
1) take a pretrained caffemodel for googlenet.
2) convert to IR
3) quantize to fp16
4) run anntest
throws the following error
"MIOpen-1.7.1/src/ocl/convolutionocl.cpp:1129: Fwd Convolution cannot be executed due to incorrect params"

**Comment by kiritigowda** [comment]
@paveltc is this a MIOpen bug? can we transfer this issue to them?

**Comment by paveltc** [comment]
I have already filed this issue to them.

**Comment by kiritigowda** [comment]
This bug has been reported to MIOpen team.
