### ISSUE TITLE
Remove system path from cmakelists.txt

### ISSUE THREAD

**Issue by haampie** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#583]
Could you please drop this absolute path `/opt/rocm/mivisionx/include` from https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/blob/master/utilities/mv_deploy/CMakeLists.txt#L27

Ref https://github.com/spack/spack/pull/25159

**Comment by kiritigowda** [comment]
@haampie thanks for pointing out this issue, #584 will solve this issue.

**Comment by kiritigowda** [comment]
#584 merged

**Comment by haampie** [comment]
Thank you!
