### ISSUE TITLE
Vision Tests - Tests Missing

### ISSUE THREAD

**Issue by kiritigowda** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#597]
**Issue** - Vision Test in V 1.2.1 had all functions from 1.3 listed in the performance test. With V 1.2.2 most of the nodes are missing.

List of all tests - https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/blob/c96cf7f6059b983ad92334f1a66a3927dd5307aa/tests/vision_tests/runVisionTests.py#L92

**resolution** - need to add all nodes in performance tests.

**Comment by LakshmiKumar23** [comment]
@kiritigowda Turns out these tests are commented out due to lack of support from runVX for some of the tests. Maybe can combine this issue and issue #578 once @asalmanp figures out what the missing functionalities are.

**Comment by kiritigowda** [comment]
@paveltc can you add a runvx feature to process "NULL"

**Comment by kiritigowda** [comment]
any updates on this issue?

**Comment by kiritigowda** [comment]
Vision functions added into test scripts.
