### ISSUE TITLE
CI:Jenkins - Training Test for rocAL

### ISSUE THREAD

**Issue by kiritigowda** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#635]
* Add Training with rocAL to CI Flow
* Training with rocAL
  + Classification
  + Detection
  + Segmentation ?

**Comment by LakshmiKumar23** [comment]
@kiritigowda Opened [issue on rocAL repo](https://github.com/ROCmSoftwarePlatform/rocAL/issues/10). Please close this issue
