### ISSUE TITLE
MIVisionX App update - Validation toolkit

### ISSUE THREAD

**Issue by LakshmiKumar23** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#644]
Need to update [mivisionx_validation_toolkit](https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/tree/master/apps/mivisionx_validation_tool) after MCW submits new python package for rocAL. 
Also needs to use python3 with this update

**Comment by kiritigowda** [comment]
@LakshmiKumar23 is this ready? can we close this issue?

**Comment by LakshmiKumar23** [comment]
@kiritigowda Python API isn't ready yet.

**Comment by kiritigowda** [comment]
> @kiritigowda Python API isn't ready yet.

add the feature required to this issue and we can track it.

**Comment by LakshmiKumar23** [comment]
Fixed by #827
