### ISSUE TITLE
OpenCL Include Link Error

### ISSUE THREAD

**Issue by kiritigowda** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#67]
* MIVisionX/amd_openvx_extensions/amd_nn/CMakeLists.txt
* MIVisionX/apps/cloud_inference/server_app/CMakeLists.txt
 
needs

````
include_directories(${OpenCL_INCLUDE_DIRS})
````

**Comment by kiritigowda** [comment]
@LakshmiKumar23 Please verify if this fix does not break the normal flow in Linux.

**Comment by LakshmiKumar23** [comment]
@kiritigowda Tested this after adding 
`include_directories(${OpenCL_INCLUDE_DIRS})`
and it builds completely.

**Comment by kiritigowda** [comment]
@LakshmiKumar23 create a pull request with those changes.
