### ISSUE TITLE
MIVisionX.sln file - missing vx_winml 

### ISSUE THREAD

**Issue by LakshmiKumar23** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#674]
@kiritigowda Can you please modify windows to build vx_winml.lib. The apps are failing because this library file is not found

**Comment by kiritigowda** [comment]
@LakshmiKumar23 this is only for WinML flow and not the main?

**Comment by kiritigowda** [comment]
Use this SLN - https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/blob/master/amd_openvx_extensions/amd_winml.sln

**Comment by LakshmiKumar23** [comment]
@kiritigowda Created PR #675
