### ISSUE TITLE
rocAL - Rename rali to rocal in MIVisionX/utilities/rali

### ISSUE THREAD

**Issue by paveltc** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#677]
We need to rename all of the folders and files with rali in the name to rocal in the MIVisionX/utilities/rali folder.
We need to check if this will break any of the current workflow.
I will take care of renaming the unit and performance tests and updating the paths.

**Comment by kiritigowda** [comment]
#766 to fix this issue

**Comment by kiritigowda** [comment]
@paveltc will you change the folder names here - https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/tree/master/utilities/rali ? or the unit test folder is good enough for this issue?

**Comment by kiritigowda** [comment]
Fixed on TOT
