### ISSUE TITLE
Help Needed - CV & ML on AMD E9171 GPU 

### ISSUE THREAD

**Issue by drvshavva** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#679]
Hi, is ti possible to use MIVisionX with amd e9171 gpu ? If can not, do you know, how can use nnef or onnx file with this gpu ?

**Comment by kiritigowda** [comment]
@drvshavva what operating system is this machine configured? MIVisionX is supported on all ROCm supported hardware. We have not personally tested our software on this GPU, but you can try it with our build and install instructions. Are you looking to use OpenVX for inference?

**Comment by drvshavva** [comment]
yes, I want to use OpenVX for inference in this GPU

**Comment by kiritigowda** [comment]
@drvshavva here is a tutorial to use inference with OpenVX - https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/tree/master/samples/model_compiler_samples#mivisionx-model-compiler-samples

Please try this and let me know if you have any problems.

**Comment by drvshavva** [comment]
thank you so much. I will share with you when I try and get results.

**Comment by kiritigowda** [comment]
> thank you so much. I will share with you when I try and get results.

Thanks! Please share the results and any feedback with the flow.

**Comment by kiritigowda** [comment]
@drvshavva any updates on this issue? Were you able to install and run any samples?

**Comment by drvshavva** [comment]
> @drvshavva any updates on this issue? Were you able to install and run any samples?

hi, my team changed the decision and bought another gpu so I couldn't. But I am very grateful for your help and answers.
