### ISSUE TITLE
rali_unittests fails to build with HIP backend

### ISSUE THREAD

**Issue by paveltc** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#687]
rali_unittests app fails to build with the HIP backend.
Throws error:
fatal error: rali_api.h: No such file or directory
 #include "rali_api.h"

**Comment by asalmanp** [comment]
@paveltc is this a regression? if so, could you please help find the PR that broke the rail_unittests?

**Comment by paveltc** [comment]
@asalmanp I can no longer reproduce this issue on my system with TOT.
