### ISSUE TITLE
rocAL - New Python APIs

### ISSUE THREAD

**Issue by LakshmiKumar23** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#698]
> @kiritigowda Python API isn't ready yet.

add the feature required to this issue and we can track it.

_Originally posted by @kiritigowda in https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/issues/644#issuecomment-982897673_

**Comment by LakshmiKumar23** [comment]
@kiritigowda MCW will make a PR for this

**Comment by kiritigowda** [comment]
@LakshmiKumar23 please follow-up with MCW.

**Comment by LakshmiKumar23** [comment]
> @LakshmiKumar23 please follow up with MCW.

Yes, @rrawther and I are tracking it

**Comment by kiritigowda** [comment]
#724 added to fix this

**Comment by kiritigowda** [comment]
@LakshmiKumar23 is this issue resolved?

**Comment by LakshmiKumar23** [comment]
@kiritigowda Yes, this was resolved with #724 and #817
