### ISSUE TITLE
Build Failure seen for mivisionx@4.5.0 in Spack environment when using with cmake@3.22.x

### ISSUE THREAD

**Issue by srekolam** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#740]
I am observing build failure when building the mivisionx@4.5.0 from the sources in the spack environment. I have root caused it to cmake@3.22.x . the latest version of the cmake being used the spack:develop branch is the cmake@3.22.1 . The mivisionx@4.5.0 or mivisionx@4.3.1 is able to build succesfully when used with cmake@3.21.4 .
seeing something as below for 4.3.1, 
 [ 21%] Building CXX object amd_openvx/openvx/CMakeFiles/openvx.dir/api/vx_nodes.cpp.o
     179    cd /tmp/root/spack-stage/spack-stage-mivisionx-4.3.1-omykae7rhuwtoyhec46hmkpypwy37whq/spack-build-omykae7/amd_ope
            nvx/openvx && /spack/lib/spack/env/gcc/g++ -DCL_TARGET_OPENCL_VERSION=220 -DENABLE_HIP=0 -DENABLE_OPENCL=1 -Dopen
            vx_EXPORTS -I/tmp/root/spack-stage/spack-stage-mivisionx-4.3.1-omykae7rhuwtoyhec46hmkpypwy37whq/spack-src/amd_ope
            nvx/openvx/include -I/tmp/root/spack-stage/spack-stage-mivisionx-4.3.1-omykae7rhuwtoyhec46hmkpypwy37whq/spack-src
            /amd_openvx/openvx/ago -I/tmp/root/spack-stage/spack-stage-mivisionx-4.3.1-omykae7rhuwtoyhec46hmkpypwy37whq/spack
            -src/amd_openvx/openvx/api -I/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.3.1/rocm-opencl-4.3.1-uzvzdnko7g
            hztnerj3b3syapxhawregv/include -I/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.3.1/rocm-opencl-4.3.1-uzvzdn
            ko7ghztnerj3b3syapxhawregv/include/Headers -I/spack/opt/spack/linux-centos7-skylake_avx512/gcc-7.3.1/protobuf-3.1
            8.0-qjdkaluiywaug63k2joowgmkkqo2kxz3/include -O3 -s -msse4.2 -std=c++14 -msse4.2 -std=c++11 -O3 -DNDEBUG -fPIC -M
            D -MT amd_openvx/openvx/CMakeFiles/openvx.dir/api/vx_nodes.cpp.o -MF CMakeFiles/openvx.dir/api/vx_nodes.cpp.o.d -
            o CMakeFiles/openvx.dir/api/vx_nodes.cpp.o -c /tmp/root/spack-stage/spack-stage-mivisionx-4.3.1-omykae7rhuwtoyhec
            46hmkpypwy37whq/spack-src/amd_openvx/openvx/api/vx_nodes.cpp
     180    /tmp/root/spack-stage/spack-stage-mivisionx-4.3.1-omykae7rhuwtoyhec46hmkpypwy37whq/spack-src/amd_openvx/openvx/ag
            o/ago_util_opencl.cpp: In function 'int agoGpuOclSetKernelArgs(cl_kernel, vx_uint32&, AgoData*, bool, vx_uint32,
            vx_uint32)':
  >> 181    /tmp/root/spack-stage/spack-stage-mivisionx-4.3.1-omykae7rhuwtoyhec46hmkpypwy37whq/spack-src/amd_openvx/openvx/ag
            o/ago_util_opencl.cpp:730:23: error: 'union cl_int2' has no member named 's0'; did you mean 's'?
     182                     value.s0 = data->u.thr.threshold_lower.S16;
     183                           ^~
     184                           s
  >> 185    /tmp/root/spack-stage/spack-stage-mivisionx-4.3.1-omykae7rhuwtoyhec46hmkpypwy37whq/spack-src/amd_openvx/openvx/ag
            o/ago_util_opencl.cpp:731:23: error: 'union cl_int2' has no member named 's1'; did you mean 's'?
     186                     value.s1 = data->u.thr.threshold_upper.S16;
     187                           ^~
     188                           s
  >> 189    /tmp/root/spack-stage/spack-stage-mivisionx-4.3.1-omykae7rhuwtoyhec46hmkpypwy37whq/spack-src/amd_openvx/openvx/ag
            o/ago_util_opencl.cpp:741:23: error: 'union cl_uint2' has no member named 's0'; did you mean 's'?
     190                     value.s0 = data->u.thr.threshold_lower.U8;
     191                           ^~
     192                           s
[mivisionx_failed.log](https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/files/7933330/mivisionx_failed.log)

**Comment by kiritigowda** [comment]
@srekolam can you try TOT master with cmake 3.22.X ?

**Comment by srekolam** [comment]
@kiritigowda  usually we use the sources from the release and build. If you have a commit-id that fixes the issue, i can use that as a patch for 4.5.0 or 4.5.2 release. Let me know if that works ? Otherwise, i can re-test it for 5.0 release once the sources are tagged.

**Comment by kiritigowda** [comment]
@srekolam the TOT master and the 5.0 release branch have added the support for cmake 3.22.X. Please verify and let us know.

**Comment by kiritigowda** [comment]
@srekolam any updates on this issue? Is this fixed with TOT?

**Comment by srekolam** [comment]
I am currently updating the rocm recipes for 5.0.0 release. I will keep you updated once i have verified the same. or if you have commitid i can verify it on the existing release too

**Comment by srekolam** [comment]
i just verified that the issue is resolved when using cmake-3.22.2 for mivisionx for rocm-5.0.0 release. Thanks for looking into it and providing the fix. i will be upstreaming the recipe updates soon.
