### ISSUE TITLE
OpenVX - vxCreateThreshold runtime failure

### ISSUE THREAD

**Issue by kiritigowda** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#759]
Runtime Failure
```
vxCreateThreshold(context, VX_THRESHOLD_TYPE_RANGE, VX_TYPE_UINT8);
```

Failure
```
libc++abi: terminating with uncaught exception of type std::invalid_argument: stoi: no conversion
zsh: abort
```

Fails at - https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/blob/fab7c1cd22036570ae6da3c9fd0b1442e3681928/amd_openvx/openvx/ago/ago_util.cpp#L1515

## Test Case

canny cpp test - samples/c_samples/canny

**Comment by kiritigowda** [comment]
@LakshmiKumar23 we still have the `vxCreateThreshold` API - we might have to move this to backward compatibility issue, lets review

**Comment by LakshmiKumar23** [comment]
> @LakshmiKumar23 we still have the `vxCreateThreshold` API - we might have to move this to a backward compatibility issue, lets review

@kiritigowda Yes, we should move it. The new spec doesn't support it at all

**Comment by hansely** [comment]
@kiritigowda @LakshmiKumar23 App working after the recent fix

**Comment by kiritigowda** [comment]
OpenVX 1.3 Support on TOT and OpenVX 1.0.1 support with MIVisionX-lite
