### ISSUE TITLE
amd_media - add hwencode mode through vaapi 

### ISSUE THREAD

**Issue by rrawther** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#779]

**Comment by kiritigowda** [comment]
@asalmanp do we have to do anything at MIVisionX? can we close this issue?

**Comment by asalmanp** [comment]
> @asalmanp do we have to do anything at MIVisionX? can we close this issue?

@kiritigowda We can close this issue. We'll do this feature outside of MIVisionX in a separate library.
