### ISSUE TITLE
Setup Script - install MIVX without root permission

### ISSUE THREAD

**Issue by zjin-lcf** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#795]
The script MIVisionX-setup.py needs sudo permission. I don’t have sudo permission on a machine where ROCm has been installed at /opt/rocm. Thank you for making a script that does not need root permission for users.

**Comment by kiritigowda** [comment]
@zjin-lcf -- as the setup currently installs the Linux packages which are required (i.e -- [install](https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/blob/834065559f213d8b188b63c7b94888c90fb6d293/MIVisionX-setup.py#L224)), this required admin access. But the workaround for this is to run the setup inside a docker/singularity or use pre-built dockers -- `docker pull mivisionx/ubuntu-20.04:opencl` or `docker pull mivisionx/ubuntu-20.04:hip `

Let me know if this would work for you?

**Comment by zjin-lcf** [comment]
Thanks.
