### ISSUE TITLE
graph.nnef Parse error

### ISSUE THREAD

**Issue by srohit0** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#8]
Using latest amdovx-modules repo to convert nnef to openvx gives me this error

> OK: parsing /home/amd/models/nnef/object_detection//mobilenet_v1_1/graph.nnef ...
> Parse error: [2:12] expected token 'graph', found ';'

### NNEF model excerpt
```
 
 version 1.0;

 graph mobilenet_v1_1( input ) -> ( output )
 {
```

### Script
```
MODEL=mobilenet_v1_1
IN_DIR=/home/amd/models/nnef/object_detection/
OUT_DIR=/home/amd/models/openvx/object_detection/

mkdir ${OUT_DIR}/$MODEL
nnef2openvx ${IN_DIR}/$MODEL ${OUT_DIR}/$MODEL
```

### Output

> OK: parsing /home/amd/models/nnef/object_detection//mobilenet_v1_1/graph.nnef ...
> Parse error: [2:12] expected token 'graph', found ';'

### NNEF specification

[Section 3.2.4 of NNEF Specification Version 1.0, Revision 3, 2018-06-13](https://www.khronos.org/registry/NNEF/specs/1.0/nnef-1.0.html#document) states that semicolon **;** is part of version statement.  Here is excerpt from the specification:

> The version info is introduced by the version keyword, and is defined by a real-number numeric literal as major and minor versions separated by a dot:
> 
> \<version> ::= "**version**" \<numeric-literal> ";"

Fix is needed to support [NNEF Specification Version 1.0, Revision 3, 2018-06-13](https://www.khronos.org/registry/NNEF/specs/1.0/nnef-1.0.html#document)

**Comment by hansely** [comment]
This issue will be resolved after the nnir_to_nnef.py fix pull request.

**Comment by kiritigowda** [comment]
@hansely is this issue fixed?

**Comment by kiritigowda** [comment]
refer to issue #54
