### ISSUE TITLE
make build failure on MacOS 12.3

### ISSUE THREAD

**Issue by tralfamadude** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#826]
Following the instructions for MacOS 12.3, on step 4 (make, after cmake) the following errors appear (seems to be undeclared identifier, too few args, asm error): 

`[  1%] Building CXX object amd_openvx/openvx/CMakeFiles/openvx.dir/ago/ago_drama.cpp.o
clang: warning: argument unused during compilation: '-msse4.2' [-Wunused-command-line-argument]
In file included from /ML_related/ws/MIVisionX/amd_openvx/openvx/ago/ago_drama.cpp:24:
In file included from /ML_related/ws/MIVisionX/amd_openvx/openvx/ago/ago_internal.h:27:
In file included from /ML_related/ws/MIVisionX/amd_openvx/openvx/ago/ago_platform.h:59:
In file included from /Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/x86intrin.h:13:
/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/ia32intrin.h:200:10: error: use of undeclared identifier '__builtin_ia32_readeflags_u32'
  return __builtin_ia32_readeflags_u32();
         ^
/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/ia32intrin.h:206:3: error: use of undeclared identifier '__builtin_ia32_writeeflags_u32'
  __builtin_ia32_writeeflags_u32(__f);
  ^
/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/ia32intrin.h:288:10: error: use of undeclared identifier '__builtin_ia32_crc32qi'
  return __builtin_ia32_crc32qi(__C, __D);
         ^
/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/ia32intrin.h:309:10: error: use of undeclared identifier '__builtin_ia32_crc32hi'; did you mean '__builtin_arm_crc32h'?
  return __builtin_ia32_crc32hi(__C, __D);
         ^
/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/ia32intrin.h:309:10: note: '__builtin_arm_crc32h' declared here
/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/ia32intrin.h:330:10: error: use of undeclared identifier '__builtin_ia32_crc32si'
  return __builtin_ia32_crc32si(__C, __D);
         ^
/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/ia32intrin.h:358:10: error: use of undeclared identifier '__builtin_ia32_rdpmc'; did you mean '__builtin_arm_dmb'?
  return __builtin_ia32_rdpmc(__A);
         ^
/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/ia32intrin.h:358:10: note: '__builtin_arm_dmb' declared here
/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/ia32intrin.h:358:10: error: argument to '__builtin_arm_dmb' must be a constant integer
  return __builtin_ia32_rdpmc(__A);
         ^                    ~~~
/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/ia32intrin.h:364:10: error: use of undeclared identifier '__builtin_ia32_rdtscp'; did you mean '__builtin_arm_rsrp'?
  return __builtin_ia32_rdtscp(__A);
         ^
/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/ia32intrin.h:364:10: note: '__builtin_arm_rsrp' declared here
/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/ia32intrin.h:364:32: error: cannot initialize a parameter of type 'const char *' with an lvalue of type 'unsigned int *'
  return __builtin_ia32_rdtscp(__A);
                               ^~~
/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/ia32intrin.h:373:3: error: use of undeclared identifier '__builtin_ia32_wbinvd'
  __builtin_ia32_wbinvd();
  ^
In file included from /ML_related/ws/MIVisionX/amd_openvx/openvx/ago/ago_drama.cpp:24:
In file included from /ML_related/ws/MIVisionX/amd_openvx/openvx/ago/ago_internal.h:27:
In file included from /ML_related/ws/MIVisionX/amd_openvx/openvx/ago/ago_platform.h:59:
In file included from /Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/x86intrin.h:15:
In file included from /Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/immintrin.h:13:
In file included from /Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/x86gprintrin.h:15:
/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/hresetintrin.h:42:27: error: invalid input constraint 'a' in asm
  __asm__ ("hreset $0" :: "a"(__eax));
                          ^
In file included from /ML_related/ws/MIVisionX/amd_openvx/openvx/ago/ago_drama.cpp:24:
In file included from /ML_related/ws/MIVisionX/amd_openvx/openvx/ago/ago_internal.h:27:
In file included from /ML_related/ws/MIVisionX/amd_openvx/openvx/ago/ago_platform.h:59:
In file included from /Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/x86intrin.h:15:
In file included from /Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/immintrin.h:17:
/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:33:5: error: use of undeclared identifier '__builtin_ia32_emms'; did you mean '__builtin_isless'?
    __builtin_ia32_emms();
    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/math.h:670:12: note: '__builtin_isless' declared here
    return isless(__lcpp_x, __lcpp_y);
           ^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/math.h:545:22: note: expanded from macro 'isless'
#define isless(x, y) __builtin_isless((x),(y))
                     ^
In file included from /ML_related/ws/MIVisionX/amd_openvx/openvx/ago/ago_drama.cpp:24:
In file included from /ML_related/ws/MIVisionX/amd_openvx/openvx/ago/ago_internal.h:27:
In file included from /ML_related/ws/MIVisionX/amd_openvx/openvx/ago/ago_platform.h:59:
In file included from /Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/x86intrin.h:15:
In file included from /Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/immintrin.h:17:
/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:33:25: error: too few arguments to function call, expected 2, have 0
    __builtin_ia32_emms();
    ~~~~~~~~~~~~~~~~~~~~^
/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:50:19: error: use of undeclared identifier '__builtin_ia32_vec_init_v2si'
    return (__m64)__builtin_ia32_vec_init_v2si(__i, 0);
                  ^
/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:67:12: error: use of undeclared identifier '__builtin_ia32_vec_ext_v2si'
    return __builtin_ia32_vec_ext_v2si((__v2si)__m, 0);
           ^
/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:129:19: error: use of undeclared identifier '__builtin_ia32_packsswb'
    return (__m64)__builtin_ia32_packsswb((__v4hi)__m1, (__v4hi)__m2);
                  ^
/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:159:19: error: use of undeclared identifier '__builtin_ia32_packssdw'
    return (__m64)__builtin_ia32_packssdw((__v2si)__m1, (__v2si)__m2);
                  ^
/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:189:19: error: use of undeclared identifier '__builtin_ia32_packuswb'
    return (__m64)__builtin_ia32_packuswb((__v4hi)__m1, (__v4hi)__m2);
                  ^
/Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/mmintrin.h:216:19: error: use of undeclared identifier '__builtin_ia32_punpckhbw'
    return (__m64)__builtin_ia32_punpckhbw((__v8qi)__m1, (__v8qi)__m2);
                  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [amd_openvx/openvx/CMakeFiles/openvx.dir/ago/ago_drama.cpp.o] Error 1
make[1]: *** [amd_openvx/openvx/CMakeFiles/openvx.dir/all] Error 2
make: *** [all] Error 2
`

**Comment by tralfamadude** [comment]
Additional info:  arm64 

The first (harmless) warning is about -msse4.2  which is an Intel directive and not useful for ARM.

**Comment by tralfamadude** [comment]
@kiritigowda  Any suggestions for getting MIVisionX working on MacOS on ARM64?

**Comment by kiritigowda** [comment]
@tralfamadude -- MIVisionX is only supported with `x86_64`/`AMD64` architecture. You can install `Rosetta 2` to emulate x86 code on ARM. Follow this issue for info -- https://github.com/Homebrew/brew/issues/9173

**Comment by kiritigowda** [comment]
@tralfamadude hope this has resolved your issue. Please reopen the issue if you are facing build issues with the x86_64 setup.
