### ISSUE TITLE
SPACK - CMakeList: directory layout not compatible

### ISSUE THREAD

**Issue by srekolam** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#830]
I looked at the CMakeLists.txt and in many places there is assumption  that all of the rocm packages are installed next to each other in a common root like
/opt/rocm
  OpenCL
  HIP
For Spack installation this does not hold, since the names are versioned.
In Spack, Opencl package is installed in install prefix path that is something like below - 
/spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.4.1/rocm-opencl-5.1.0-36voaze6ir45zqknhecv4che32apn6li

Eg- inside FindOpenCL.cmake- 
**if(EXISTS "${ROCM_PATH}/opencl/lib/libOpenCL.so")**
        if(NOT "${OPENCL_LIBRARIES}" STREQUAL "${ROCM_PATH}/opencl/lib/libOpenCL.so")
            message("-- ${White}OpenCL Found - ${OPENCL_LIBRARIES}${ColourReset}")
            message("-- ${White}ROCm OpenCL Found - Force OpenCL_LIBRARIES & OpenCL_INCLUDE_DIRS to use ROCm OpenCL${ColourReset}")
            set(OpenCL_LIBRARIES ${ROCM_PATH}/opencl/lib/libOpenCL.so CACHE INTERNAL "")
            set(OpenCL_INCLUDE_DIRS ${ROCM_PATH}/opencl/include CACHE INTERNAL "")
        endif()

if(EXISTS ${ROCM_PATH}/miopen/include/miopen/config.h)
            file(READ ${ROCM_PATH}/miopen/include/miopen/config.h MIOPEN_CONFIG_FILE)
            string(REGEX MATCH "MIOPEN_BACKEND_OPENCL ([0-9]*)" _ ${MIOPEN_CONFIG_FILE})
            set(MIOPEN_BACKEND_OPENCL_FOUND ${CMAKE_MATCH_1})
            string(REGEX MATCH "MIOPEN_BACKEND_HIP ([0-9]*)" _ ${MIOPEN_CONFIG_FILE})
            set(MIOPEN_BACKEND_HIP_FOUND ${CMAKE_MATCH_1})

Seen refering to include directories and link directories using for eg- include_directories (/opt/rocm/mivisionx/include) and (/opt/rocm/mivisionx/lib)

**Comment by kiritigowda** [comment]
@srekolam is your build script using TOT Master or some other branch?

**Comment by srekolam** [comment]
i used the rocm-5.0.2 source archive for the above. I have patched it in my spack recipe for some of the above issues mentioned but when i compile it for backend=HIP i see a build failure. the backend=opencl succeeds . I have also tried the rocm-5.1.0 sources for mivisionx and see same issue
[mivisionx-5.1.0-backend_HIP-spack-build-out.txt](https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/files/8616945/mivisionx-5.1.0-backend_HIP-spack-build-out.txt)

**Comment by kiritigowda** [comment]
@srekolam can you test with this PR -- https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/pull/833

**Comment by srekolam** [comment]
sure..  will do.

**Comment by kiritigowda** [comment]
@srekolam any updates on this?

**Comment by srekolam** [comment]
@kiritigowda  i will need @5.2.0 sources for verifying it. I will update once those are available and i am able to update the spack rcom recipes for rocm-5.2.0.

**Comment by kiritigowda** [comment]
@srekolam any updates on this issue? is this resolved?

**Comment by srekolam** [comment]
@kiritigowda , we are currently updating the spack recipes for 5.2.0. I will be able to update you with in next 2-3 days ..

**Comment by srekolam** [comment]
i am able to build mivisionx for bothe HIP and OPENCL backend.. I will touchbase with you with regard amdrpp and rocAL
Below  are the list of libraries that are generated for OPENCL backend :
libopenvx.so        libvx_amd_media.so  libvx_loomsl.so     libvx_opencv.so     libvxu.so
The binaries below are generated for OPENCL backed -
loom_shell  mv_compile  runcl       runvx

I do see this though - 
 NOTE: FindAMDRPP failed to find -- amd_rpp
-- WARNING: /opt/rocm/miopen/include/miopen/config.h file Not Found. please run the setup script to install the MIOpen package

For the backend = HIP i am able to build succesfully which was failing in earlier releases. Thanks for looking into this
I see the below binaries : 
mv_compile  runvx
i see the below shared libraries : 
libopenvx.so        libvx_amd_media.so  libvx_opencv.so     libvxu.so

I do see this with backend=HIP as well 

    NOTE: FindAMDRPP failed to find -- amd_rpp
-- NOTE: FindTurboJpeg failed to find -- turbojpeg
-- hip::amdhip64 is SHARED_LIBRARY
-- Found HIP for rocAL: 5.2.0/spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.4.1/hip-5.2.0-4lwedvonu3mvdiqcw6kh5vvaklffu7xi
-- NOTE: rocAL library requires AMD's rpp library, Not Found
-- NOTE: rocAL library requires TurboJpeg, Not Found
-- WARNING: rocAL module excluded

**Comment by kiritigowda** [comment]
@srekolam thanks for the updates, I will look into this.

**Comment by srekolam** [comment]
I will close this ticket. As discussed with @kiritigowda i will open couple of issues with the logs for
1. enabling rocAL and rpp library which currently is not building.
    NOTE: rocAL library requires AMD's rpp library, Not Found
-- NOTE: rocAL library requires TurboJpeg, Not Found
-- WARNING: rocAL module excluded
2. when backend=HIP is enabled, it was trying to find hard coded reference to the /opt/rocm/miopen/include/miopen/config.h file and reports Not Found error . In Spack we have 2 recipes, miopen-hip and miopen-opencl. if i make changes to mivisionx in Spack so that it is able to find the config.h based on the CMAKE_INSTALL_PREFIX for miopen-hip or miopen-opencl, then the build proceeds further but fails later on for backend=HIP.  I will provide further logs to see if this can be looked at further.
