### ISSUE TITLE
Upgrade ffmpeg to 4.4.x for AV1 decoder enablement.

### ISSUE THREAD

**Issue by rrawther** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#861]
AV1 encoding with and without HW acceleration is only supported in ffmpeg 4.4 versions and above. Also this needs installing libdav1d which worked only from source installation in my experement.
@kiritigowda : can you please try putting this in setup scripts.

**Comment by kiritigowda** [comment]
@rrawther -- Testing with this version -- https://github.com/FFmpeg/FFmpeg/releases/tag/n4.4

Is this good?

**Comment by kiritigowda** [comment]
FFMPEG -- `4.4.2` set as the default install. Missing libdAV1D install

**Comment by kiritigowda** [comment]
@rrawther do you still need any updates or current TOT changes in setup good?

**Comment by kiritigowda** [comment]
@rrawther please reopen this issue if the setup is not installing the required deps.
