### ISSUE TITLE
rocAL - augmentation output has bluish tint 

### ISSUE THREAD

**Issue by rrawther** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#880]
Need to investigate this issue

**Comment by kiritigowda** [comment]
@LakshmiKumar23 any updates on this?

**Comment by LakshmiKumar23** [comment]
@kiritigowda Not yet, let me confirm with MCW in tomorrow's meeting

**Comment by kiritigowda** [comment]
Re-open if seen
