### ISSUE TITLE
nnef2openvx : min *** not yet supported ***

### ISSUE THREAD

**Issue by srohit0** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#9]
Using latest MIVision repo to convert nnef to openvx gives me this error

> min *** not yet supported ***

### NNEF Model excerpt

```
version 1.0 
graph mobilenet_v1_1( input ) -> ( output )
{
     mobilenetv1_mobilenetv1_conv2d_0_relu6 = min(y = 6.0, x = mobilenetv1_mobilenetv1_conv2d_0_relu6_relu);

}
```

### Command
```
nnef2openvx  \
    /home/amd/models/nnef/object_detection/mobilenet_v1_1 \
    /home/amd/models/openvx/object_detection/mobilenet_v1_1
```

### Output

> OK: parsing /home/amd/models/nnef/object_detection/mobilenet_v1_1/graph.nnef ...
> min *** not yet supported ***
> [openvx]$ vi /home/amd/models/nnef/object_detection/mobilenet_v1_1/graph.nnef
> 

min is a basic simplifier operation supported in [NNEF specification 1.0](https://www.khronos.org/registry/NNEF/specs/1.0/nnef-1.0.html#_simplifier_operations).

### Does the converter lack full support of NNEF specification 1.0 or am I using it wrong?

regards

**Comment by kiritigowda** [comment]
Issue #54 addresses this bug
