### ISSUE TITLE
rocAL - SSD training doesn't converge with MIVisionX TOT

### ISSUE THREAD

**Issue by LakshmiKumar23** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#927]
@swetha097 Opening an issue to track the SSD issue

**Comment by LakshmiKumar23** [comment]
@swetha097 we are still seeing issues with --prefetch for NHWC script right?

**Comment by swetha097** [comment]
I think there is no issue with convergence @LakshmiKumar23 , with the lastest rocm 5.2.3 docker, we see it going to a hanged state / leading to HSA_STATUS_ERROR_MEMORY_APERTURE_VIOLATION.
All trainings work on rocm5.2.0 docker
