### ISSUE TITLE
-DCMAKE_BUILD_TYPE=Debug flag not working

### ISSUE THREAD

**Issue by LakshmiKumar23** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#966]
Debug mode is not working on any of our libraries. The step in just falls through
@rrawther @kiritigowda @asalmanp

**Comment by rrawther** [comment]
I think the MIVIsionX is built without debug information even when specifying CMAKE_BUILD_TYPE=Debug. This was working few months ago. Some of the recent CMake changes broke this. Currently we can't debug any MIVisionX libs using VScode

**Comment by LakshmiKumar23** [comment]
@rrawther Seems like we need to have gdb version 12.1 to debug HIP backend. Installation instructions
```
sudo apt update
sudo apt install build-essential texinfo
sudo apt-get install libgmp-dev
cd ~
wget https://ftp.gnu.org/gnu/gdb/gdb-12.1.tar.gz
tar -xvzf gdb-12.1.tar.gz
cd gdb-12.1
./configure --with-python
make CXXFLAGS="-static-libstdc++"  -j16
sudo make install -j16
```

**Comment by kiritigowda** [comment]
Add setup --debug option --- @kiritigowda

**Comment by kiritigowda** [comment]
Issue #969 to add the feature
