### ISSUE TITLE
rocal_pybind - wheel not reinstalling when there are changes to wheel package

### ISSUE THREAD

**Issue by rrawther** [GPUOpen-ProfessionalCompute-Libraries/MIVisionX#980]
Happens when running run.sh shell script.
It looks at the version installed and won't reinstall if we make changes

**Comment by rrawther** [comment]
@swetha097 : Can you look into this issue

**Comment by swetha097** [comment]
@rrawther , 
I have created a PR as a ix for this.
[https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/pull/982](https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/pull/982)

This uninstalls the wheel pkg, then installs it.

**Comment by LakshmiKumar23** [comment]
@kiritigowda This issue can be closed. Fixed in PR982.
